import fs from 'node:fs/promises';
import path from 'node:path';
import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const base=path.dirname(new URL(import.meta.url).pathname.slice(1)),out=path.join(base,'deliverables'),qa=path.join(base,'qa');
await fs.mkdir(out,{recursive:true});await fs.mkdir(qa,{recursive:true});const d=JSON.parse(await fs.readFile(path.join(base,'content.json'),'utf8'));
const nav='#1F4E78',yellow='#FFF2CC',green='#E2F0D9',red='#FCE4D6',line='#D9E2F3',font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function title(s,t,sub,n){s.showGridLines=false;s.getRange(`A1:${col(n)}1`).merge();s.getRange('A1').values=[[t]];s.getRange('A1').format={font:{name:font,size:16,bold:true},rowHeight:30};s.getRange(`A2:${col(n)}2`).merge();s.getRange('A2').values=[[sub]];s.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},wrapText:true,rowHeight:28}}
function head(s,a){s.getRange(a).format={fill:nav,font:{name:font,size:8,bold:true,color:'#FFFFFF'},wrapText:true,horizontalAlignment:'center',verticalAlignment:'center',rowHeight:34,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}
function body(s,a){s.getRange(a).format={font:{name:font,size:8},wrapText:true,verticalAlignment:'center',borders:{preset:'all',style:'thin',color:line}}}
function widths(s,m){for(const[k,v]of Object.entries(m))s.getRange(`${k}:${k}`).format.columnWidth=v}
function make(w,n,t,sub,h,rows,wm,tn){const s=w.worksheets.add(n);title(s,t,sub,h.length);s.getRange(`A5:${col(h.length)}5`).values=[h];head(s,`A5:${col(h.length)}5`);if(rows.length){s.getRange(`A6:${col(h.length)}${5+rows.length}`).values=rows;body(s,`A6:${col(h.length)}${5+rows.length}`);s.tables.add(`A5:${col(h.length)}${5+rows.length}`,true,tn).style='TableStyleMedium2'}widths(s,wm);s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(Math.min(3,h.length));return s}
function status(r,vals=['未开始','进行中','待复核','已完成']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{bold:true,color:'#548235'}}});r.conditionalFormats.add('containsText',{text:'高',format:{fill:red,font:{bold:true,color:'#C00000'}}})}
const w=Workbook.create();let s=w.worksheets.add('00-管理看板');title(s,'应付账款及供应商管理工具包','案例企业：华辰智造科技有限公司。账龄基准日2026-08-31，黄色区域为人工维护。',8);
s.getRange('A5:D5').values=[['指标','本期结果','管理阈值','主管动作']];head(s,'A5:D5');s.getRange('A6:A16').values=[['应付净余额'],['逾期正余额'],['逾期率'],['未来30天到期'],['暂估未到票'],['争议余额'],['应付负余额'],['冻结供应商数'],['账户变更待核验'],['逾期预付'],['Open Issue']];
s.getRange('B6:B16').formulas=[["=SUM('02-应付明细'!K6:K23)"],["=SUMIF('02-应付明细'!R6:R23,\"逾期\",'02-应付明细'!K6:K23)"],["=IF(B6=0,0,B7/B6)"],["=SUMIFS('02-应付明细'!K6:K23,'02-应付明细'!E6:E23,\">=\"&DATE(2026,9,1),'02-应付明细'!E6:E23,\"<=\"&DATE(2026,9,30),'02-应付明细'!K6:K23,\">0\")"],["=SUMIF('02-应付明细'!L6:L23,\"暂估未到票\",'02-应付明细'!K6:K23)"],["=SUMIF('02-应付明细'!M6:M23,\"是\",'02-应付明细'!K6:K23)"],["=-SUMIF('02-应付明细'!K6:K23,\"<0\",'02-应付明细'!K6:K23)"],["=COUNTIF('01-供应商主数据'!H6:H17,\"冻结\")"],["=COUNTIF('07-账户变更'!J6:J45,\"待核验\")"],["=SUMIF('10-预付跟踪'!J6:J45,\"逾期\",'10-预付跟踪'!E6:E45)"],["=COUNTIF('15-Issue Log'!N6:N65,\"Open\")"]];
s.getRange('C6:C16').values=[['结合采购额'],['逐笔'],[.1],['现金计划'],['>60天逐笔'],['逐笔'],[0],[0],[0],[0],[0]];s.getRange('D6:D16').values=[['解释采购与付款变化'],['区分无争议与争议'],['超过阈值专项分析'],['纳入13周预测'],['追发票并查真实义务'],['付款与索赔分开'],['查预付/超付/串户'],['冻结交易与付款'],['独立回拨验证'],['追履约或退款'],['Owner、日期、临时控制和Closure']];body(s,'A6:D16');s.getRange('B6:B7').format.numberFormat='¥#,##0';s.getRange('B8').format.numberFormat='0.0%';s.getRange('B9:B16').format.numberFormat='¥#,##0';widths(s,{A:24,B:18,C:18,D:50});

s=make(w,'01-供应商主数据','供应商主数据与准入','供应商创建、银行账户维护、发票处理和付款职责应分离。',['编码','供应商名称','类别','等级','纳税人类型','账期','额度','状态','责任部门','银行账户','复评到期日','说明'],d.suppliers,{A:12,B:28,C:18,D:10,E:15,F:14,G:15,H:12,I:14,J:20,K:15,L:38},'Suppliers');s.getRange('G6:L17').format.fill=yellow;s.getRange('G6:G17').format.numberFormat='¥#,##0';s.getRange('K6:K17').format.numberFormat='yyyy-mm-dd';s.getRange('H6:H17').dataValidation={rule:{type:'list',values:['正常','关注','冻结','退出']}};
const rows=d.ap.map((x,i)=>{const r=i+6;return [x[0],x[1],x[2],new Date(x[3]),new Date(x[4]),...x.slice(5,15),`=MAX(0,DATE(2026,8,31)-E${r})`,`=IF(P${r}=0,\"未到期\",IF(P${r}<=30,\"1-30天\",IF(P${r}<=90,\"31-90天\",IF(P${r}<=180,\"91-180天\",IF(P${r}<=365,\"181-365天\",\"365天以上\")))))`,`=IF(AND(K${r}>0,DATE(2026,8,31)>E${r}),\"逾期\",IF(K${r}<0,\"负余额\",\"未到期\"))`]});
s=make(w,'02-应付明细','应付账款未清项','到期、账龄和状态自动计算。先查实质，再处理负余额。',['应付ID','供应商编码','供应商','业务日','到期日','PO','收货/验收','发票','原值','已付','余额','业务状态','争议','责任部门','备注','逾期天数','账龄','到期状态'],rows,{A:12,B:12,C:28,D:14,E:14,F:14,G:15,H:16,I:14,J:14,K:14,L:18,M:10,N:14,O:42,P:13,Q:14,R:13},'APDetail');s.getRange('D6:E23').format.numberFormat='yyyy-mm-dd';s.getRange('I6:K23').format.numberFormat='¥#,##0';s.getRange('L6:O23').format.fill=yellow;s.getRange('R6:R23').conditionalFormats.add('containsText',{text:'逾期',format:{fill:red,font:{bold:true,color:'#C00000'}}});
let grni=d.ap.filter(x=>x[11].includes('暂估')).map((x,i)=>[`GRNI-${String(i+1).padStart(3,'0')}`,x[1],x[2],x[5],x[6],new Date(x[3]),x[10],`=MAX(0,DATE(2026,8,31)-F${i+6})`,'',x[13],'未开始','']);grni.push(...Array.from({length:37},(_,i)=>[`GRNI-${String(i+4).padStart(3,'0')}`,'','','','',null,0,'','','','', '']));
s=make(w,'03-GRNI暂估','已收货未到票与暂估','超过60天项目必须查明真实义务、发票计划和清理方案。',['GRNI ID','供应商编码','供应商','PO','收货/验收','收货日','暂估金额','账龄天数','预计到票日','责任部门','状态','差异/处理'],grni,{A:14,B:12,C:26,D:14,E:16,F:14,G:15,H:13,I:15,J:14,K:13,L:42},'GRNI');s.getRange('F6:F45').format.numberFormat='yyyy-mm-dd';s.getRange('G6:G45').format.numberFormat='¥#,##0';s.getRange('I6:I45').format.numberFormat='yyyy-mm-dd';s.getRange('I6:L45').format.fill=yellow;status(s.getRange('K6:K45'));
let match=d.ap.map((x,i)=>[`MAT-${String(i+1).padStart(3,'0')}`,x[0],x[2],x[5],x[6],x[7],x[8],x[8],x[8],x[7]?'已匹配':'缺发票',x[12],x[13],'']);
s=make(w,'04-三单匹配','PO—收货/验收—发票匹配','容差是分流规则，不替代真实性判断。',['匹配ID','应付ID','供应商','PO','收货/验收','发票','PO金额','收货金额','发票金额','匹配结果','是否争议','Owner','差异处理'],match,{A:13,B:12,C:26,D:14,E:16,F:16,G:14,H:14,I:14,J:16,K:11,L:14,M:42},'Match');s.getRange('G6:I23').format.numberFormat='¥#,##0';s.getRange('J6:M23').format.fill=yellow;
let pay=d.ap.filter(x=>x[10]>0).map((x,i)=>[`PAY-${String(i+1).padStart(3,'0')}`,x[0],x[2],new Date(x[4]),x[10],x[11],x[12],x[13],'', '', '待排程']);pay.push(...Array.from({length:42},(_,i)=>[`PAY-${String(i+17).padStart(3,'0')}`,'','',null,0,'','','','','','']));
s=make(w,'05-付款计划','未来13周付款计划','付款优先级同时考虑到期、关键供应、争议、折扣、合规和现金。',['计划ID','应付ID','供应商','到期日','余额','业务状态','争议','责任部门','优先级/理由','计划付款日','状态'],pay,{A:13,B:12,C:26,D:14,E:15,F:18,G:10,H:14,I:42,J:15,K:13},'PayPlan');s.getRange('D6:D64').format.numberFormat='yyyy-mm-dd';s.getRange('E6:E64').format.numberFormat='¥#,##0';s.getRange('I6:K64').format.fill=yellow;s.getRange('J6:J64').format.numberFormat='yyyy-mm-dd';status(s.getRange('K6:K64'),['待排程','待审批','已批准','已支付','暂缓','拒绝']);
let approvals=Array.from({length:50},(_,i)=>[`PA-${String(i+1).padStart(3,'0')}`,'','','',0,'','','','','','待审批','','']);
s=make(w,'06-付款审批','付款审批与执行','制单、复核、授权和银行执行应适当分离。',['申请号','供应商','应付ID','付款事由','金额','到期/例外依据','匹配状态','收款账户','账户变更标识','申请人','审批状态','网银流水','退汇/退款'],approvals,{A:13,B:25,C:12,D:32,E:15,F:30,G:16,H:22,I:14,J:14,K:13,L:20,M:28},'Approvals');s.getRange('B6:M55').format.fill=yellow;s.getRange('E6:E55').format.numberFormat='¥#,##0';s.getRange('K6:K55').dataValidation={rule:{type:'list',values:['待审批','批准','拒绝','已支付','退汇']}};
let changes=[['BC-001','S011','宏达贸易有限公司','6222****7180','个人账户6222****9918','2026-08-28','邮件','未完成','资金主管','待核验','','冻结付款'],...Array.from({length:39},(_,i)=>[`BC-${String(i+2).padStart(3,'0')}`,'','','','','','','','','','',''])];
s=make(w,'07-账户变更','供应商银行账户变更','禁止仅按变更邮件内的联系方式核验。',['变更ID','供应商编码','供应商','原账户','新账户','申请日期','申请渠道','独立回拨','复核人','状态','批准日','临时控制'],changes,{A:13,B:12,C:26,D:20,E:22,F:14,G:15,H:16,I:14,J:13,K:14,L:32},'BankChanges');s.getRange('D6:L45').format.fill=yellow;s.getRange('F6:F45').format.numberFormat='yyyy-mm-dd';s.getRange('K6:K45').format.numberFormat='yyyy-mm-dd';s.getRange('J6:J45').dataValidation={rule:{type:'list',values:['待核验','已核验','拒绝','已生效']}};
let rec=d.suppliers.map((x,i)=>[`REC-${String(i+1).padStart(3,'0')}`,x[0],x[1],0,0,0,'','',x[8],'未开始','']);
s=make(w,'08-供应商对账','供应商余额对账','差异不能只写“时间差”，必须定位单据和关闭动作。',['对账ID','编码','供应商','账面余额','对账单余额','差异','差异类型','处理动作','责任部门','状态','Closure证据'],rec,{A:13,B:12,C:26,D:15,E:15,F:15,G:20,H:40,I:14,J:13,K:38},'Reconciliation');s.getRange('D6:F17').format.numberFormat='¥#,##0';s.getRange('D6:K17').format.fill=yellow;status(s.getRange('J6:J17'));
let disputes=d.ap.filter(x=>x[12]=='是').map((x,i)=>[`DIS-${String(i+1).padStart(3,'0')}`,x[0],x[2],x[10],x[14],'','','',x[13],'',null,'Open','']);disputes.push(...Array.from({length:37},(_,i)=>[`DIS-${String(i+4).padStart(3,'0')}`,'','',0,'','','','','','',null,'','']));
s=make(w,'09-争议索赔','供应商争议与索赔','无争议部分和争议部分分开管理。',['争议ID','应付ID','供应商','争议金额','事项','供应商主张','公司判断','合同依据','Owner','下一步','截止日','状态','会计/付款影响'],disputes,{A:13,B:12,C:25,D:15,E:34,F:34,G:34,H:28,I:14,J:34,K:14,L:13,M:38},'Disputes');s.getRange('D6:D45').format.numberFormat='¥#,##0';s.getRange('F6:M45').format.fill=yellow;s.getRange('K6:K45').format.numberFormat='yyyy-mm-dd';s.getRange('L6:L45').dataValidation={rule:{type:'list',values:['Open','In Progress','Resolved','Closed']}};
let advances=[['ADV-001','S004','云启软件服务有限公司','PO260801',678000,new Date('2026-08-01'),new Date('2026-08-01'),'SaaS已开通，按期摊销','IT','正常',''],['ADV-002','S007','力源设备股份有限公司','PO260501',1130000,new Date('2026-05-01'),new Date('2026-08-12'),'设备已验收，转入设备结算','设备部','正常',''],['ADV-003','S011','宏达贸易有限公司','PO260601',300000,new Date('2026-06-01'),new Date('2026-07-15'),'供应商账户异常，未交货','采购二部','逾期','冻结新增预付并追款'],...Array.from({length:37},(_,i)=>[`ADV-${String(i+4).padStart(3,'0')}`,'','','',0,null,null,'','','',''])];
s=make(w,'10-预付跟踪','预付款与履约跟踪','预付后必须跟踪交付、里程碑、担保和退款权。',['预付ID','编码','供应商','合同/PO','余额','预付日','约定交付日','履约状态','Owner','状态','处理'],advances,{A:13,B:12,C:25,D:15,E:15,F:14,G:15,H:36,I:14,J:13,K:42},'Advances');s.getRange('E6:E45').format.numberFormat='¥#,##0';s.getRange('F6:G45').format.numberFormat='yyyy-mm-dd';s.getRange('H6:K45').format.fill=yellow;s.getRange('J6:J45').dataValidation={rule:{type:'list',values:['正常','关注','逾期','已结算','退款中']}};
s=make(w,'11-核心指标','应付与供应商核心指标','指标是下钻入口，不是最终结论。',['指标','定义','管理意义','恶化原因','下钻方向'],d.metrics,{A:24,B:34,C:38,D:45,E:42},'Metrics');
s=make(w,'12-月末Checklist','应付月末检查清单','每项必须有执行证据、复核和关闭标准。',['明确动作','责任人','期限','证据','关闭标准','完成状态','复核人','复核日'],d.checklist.map(x=>[...x,'未开始','',null]),{A:56,B:16,C:12,D:40,E:36,F:13,G:14,H:14},'MonthEnd');s.getRange('F6:H14').format.fill=yellow;status(s.getRange('F6:F14'));s.getRange('H6:H14').format.numberFormat='yyyy-mm-dd';
let takeover=[['第一周','供应商主数据和权限','导出主数据、银行变更日志和权限矩阵','','未开始'],['第一周','AP与GL','重做子模块总账对账','','未开始'],['第一周','GRNI','扫描60/90天以上暂估','','未开始'],['第一周','负余额和预付','穿透银行及未清项','','未开始'],['第一月','付款批次','抽查大额、账户变更、第三方和退汇','','未开始'],['第一月','供应商真实性','抽查同账户、关联关系和休眠重启','','未开始'],['第一月','逾期与中小企业款项','区分无争议到期与争议','','未开始'],['第一月','历史Issue边界','形成基准日问题清单并书面汇报','','未开始']];
s=make(w,'13-接手检查','新财务主管接手检查','记录资料、事实、临时控制和历史责任边界。',['阶段','事项','检查动作','发现/证据','状态'],takeover,{A:14,B:30,C:54,D:48,E:13},'Takeover');s.getRange('D6:E13').format.fill=yellow;status(s.getRange('E6:E13'));
s=make(w,'14-风险红旗','采购付款风险红旗','发现红旗后先控制风险，再核实和升级。',['控制','风险','控制动作','证据'],d.controls,{A:34,B:38,C:54,D:34},'RedFlags');
let issues=[['ISS-001','宏达贸易','改付个人账户且供应商已冻结','付款前检查',226000,'资金损失/欺诈','资金主管','原联系人独立核验并取得合法文件',new Date('2026-09-12'),'冻结付款和账户变更','保持应付未清','完善回拨控制','财务经理','Open',''],['ISS-002','华南塑胶','应付负余额61,000及质量争议','月结',61000,'列报/资金/争议','AP主管','穿透付款、退货和串户',new Date('2026-09-15'),'禁止跨供应商冲抵','待事实确认后调账','建立负余额月度扫描','财务主管','Open',''],['ISS-003','东莞精工','113,000元挂账18个月','供应商对账',113000,'错账/历史舞弊','AP主管','核对银行、批次和对账单',new Date('2026-09-20'),'暂停核销','证据充分后更正','年度函证与账龄清理','财务主管','In Progress',''],...Array.from({length:57},(_,i)=>[`ISS-${String(i+4).padStart(3,'0')}`,'','','',0,'','','',null,'','','','','',''])];
s=make(w,'15-Issue Log','应付Issue与Closure','Resolved后仍需验证账务、付款、主数据和流程整改。',['Issue','供应商','问题','来源','金额','影响','Owner','下一步','截止日','临时控制','会计处理','管理整改','复核人','状态','Closure证据'],issues,{A:13,B:22,C:36,D:18,E:14,F:28,G:14,H:36,I:14,J:32,K:28,L:34,M:14,N:13,O:38},'Issues');s.getRange('B6:O65').format.fill=yellow;s.getRange('E6:E65').format.numberFormat='¥#,##0';s.getRange('I6:I65').format.numberFormat='yyyy-mm-dd';s.getRange('N6:N65').dataValidation={rule:{type:'list',values:['Open','In Progress','Resolved','Closed','Accepted Risk']}};
s=make(w,'16-RACI','岗位责任矩阵','业务负责需求和履约事实，财务负责数据、支付控制、核算和监督。',['事项','执行','财务主管','协同','批准'],d.raci,{A:30,B:28,C:36,D:26,E:24},'RACI');
s=make(w,'17-案例库','应付及供应商管理案例','可用于面试、入职和月度复盘。',['编号','场景','第一步','沟通对象','处理方案','升级条件','我的回答'],d.cases.map(x=>[...x,'']),{A:12,B:40,C:52,D:28,E:52,F:40,G:52},'Cases');s.getRange('G6:G23').format.fill=yellow;
s=make(w,'18-资料来源','法规、税务与内控资料','实际处理时重新核对业务发生时有效规定。',['名称','文件号','关系','官方网址'],d.sources,{A:46,B:32,C:56,D:60},'Sources');
w.recalculate();const errors=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'final formula error scan'});await fs.writeFile(path.join(qa,'errors.ndjson'),errors.ndjson??String(errors));
for(const n of ['00-管理看板','01-供应商主数据','02-应付明细','03-GRNI暂估','04-三单匹配','05-付款计划','06-付款审批','07-账户变更','08-供应商对账','09-争议索赔','10-预付跟踪','11-核心指标','12-月末Checklist','13-接手检查','14-风险红旗','15-Issue Log','16-RACI','17-案例库','18-资料来源']){const p=await w.render({sheetName:n,autoCrop:'all',scale:.55,format:'png'});await fs.writeFile(path.join(qa,`${n}.png`),new Uint8Array(await p.arrayBuffer()))}
const file=await SpreadsheetFile.exportXlsx(w);await file.save(path.join(out,'应付账款及供应商管理工具包.xlsx'));console.log(JSON.stringify({sheets:19}));
