import fs from 'node:fs/promises';import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const base=new URL('./',import.meta.url).pathname.slice(1),out=`${base}deliverables`,qa=`${base}qa_sheets`;await fs.mkdir(out,{recursive:true});await fs.mkdir(qa,{recursive:true});const d=JSON.parse(await fs.readFile(`${base}content.json`,'utf8'));
const navy='#17365D',pale='#EAF2F8',amber='#FFF2CC',green='#E2F0D9',red='#FCE4D6',line='#D9E1E8',font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}function title(sh,t,sub,n){sh.showGridLines=false;sh.getRange(`A1:${col(n)}1`).merge();sh.getRange('A1').values=[[t]];sh.getRange('A1').format={font:{name:font,size:16,bold:true},rowHeight:30};sh.getRange(`A2:${col(n)}2`).merge();sh.getRange('A2').values=[[sub]];sh.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},rowHeight:25,wrapText:true}}
function header(sh,a){sh.getRange(a).format={fill:navy,font:{name:font,size:8,bold:true,color:'#FFFFFF'},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,rowHeight:36,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}function body(sh,a){sh.getRange(a).format={font:{name:font,size:8},verticalAlignment:'center',wrapText:true,borders:{preset:'all',style:'thin',color:line}}}function widths(sh,m){for(const[k,v]of Object.entries(m))sh.getRange(`${k}:${k}`).format.columnWidth=v}
function status(r,vals=['未开始','进行中','待复核','已完成','不适用']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{color:'#548235',bold:true}}});r.conditionalFormats.add('containsText',{text:'逾期',format:{fill:red,font:{color:'#C00000',bold:true}}});r.conditionalFormats.add('containsText',{text:'未开始',format:{fill:amber,font:{color:'#9C6500'}}})}
function sheet(wb,n,t,sub,h,rows,w,tn){const s=wb.worksheets.add(n);title(s,t,sub,h.length);s.getRange(`A5:${col(h.length)}5`).values=[h];header(s,`A5:${col(h.length)}5`);if(rows.length){s.getRange(`A6:${col(h.length)}${5+rows.length}`).values=rows;body(s,`A6:${col(h.length)}${5+rows.length}`);s.tables.add(`A5:${col(h.length)}${5+rows.length}`,true,tn).style='TableStyleMedium2'}widths(s,w);s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(2);return s}const blank=(n,f)=>Array.from({length:n},(_,i)=>f(i+1));
const wb=Workbook.create();let s=wb.worksheets.add('00-主管管理看板');title(s,'财务主管管理看板','聚焦逾期、阻断、重大风险、待升级和待Closure事项。版本日期：2026-09-10',10);s.getRange('A5:D5').values=[['管理指标','当前值','目标','说明']];header(s,'A5:D5');s.getRange('A6:A14').values=[['月结任务数'],['月结已完成'],['阻断事项'],['逾期任务'],['Open Issue'],['Pending Issue'],['Resolved待关闭'],['高风险Issue'],['完成率']];s.getRange('B6:B14').formulas=[["=COUNTA('03-月结任务表'!A6:A45)"],["=COUNTIF('03-月结任务表'!K6:K45,\"已完成\")"],["=COUNTIFS('03-月结任务表'!I6:I45,\"是\",'03-月结任务表'!K6:K45,\"<>已完成\")"],["=COUNTIFS('03-月结任务表'!F6:F45,\"<\"&TODAY(),'03-月结任务表'!K6:K45,\"<>已完成\")"],["=COUNTIF('06-Issue Log'!V6:V85,\"Open\")"],["=COUNTIF('06-Issue Log'!V6:V85,\"Pending\")"],["=COUNTIF('06-Issue Log'!V6:V85,\"Resolved\")"],["=COUNTIF('06-Issue Log'!G6:G85,\"红色\")"],["=IF(B6=0,0,B7/B6)"]];s.getRange('C6:C14').values=[[40],[40],[0],[0],[0],[0],[0],[0],[1]];s.getRange('D6:D14').values=[['月结任务表有效行'],['状态已完成'],['会阻断且未完成'],['截止日前未完成'],['已确认未开始'],['等待外部条件'],['动作完成但未验证'],['需主管立即关注'],['已完成/任务数']];body(s,'A6:D14');s.getRange('B14:C14').format.numberFormat='0%';widths(s,{A:25,B:16,C:14,D:46});
s=sheet(wb,'01-Close Calendar','Close Calendar','明确时点、R、完成证据、异常标准和升级层级。',['时点','主要任务','R执行','A负责','完成证据','异常标准','升级对象','状态'],d.close.map(x=>[x[0],x[1],x[2],'财务主管',x[3],x[4],x[5],'未开始']),{A:10,B:44,C:20,D:16,E:36,F:34,G:24,H:11},'CloseCalendar');status(s.getRange('H6:H13'));
s=sheet(wb,'02-RACI责任矩阵','财务流程RACI责任矩阵','R执行、A最终负责、C事前协商、I结果知会；每个任务应有唯一清晰A。',['流程','R执行','A最终负责','C协商','I知会','边界说明','复核频率','状态'],d.raci.map(x=>[...x,'实际任务需再拆到单据和系统动作','年度及流程变动时','未开始']),{A:20,B:30,C:28,D:25,E:22,F:38,G:20,H:11},'RACIMatrix');status(s.getRange('H6:H19'));
s=sheet(wb,'03-月结任务表','月结任务表','黄色区域由团队更新；主管只看关键路径、逾期和异常。',['编号','阶段','任务','R','A','截止时间','前置任务','完成证据','是否阻断','异常说明','状态','实际完成日','复核人'],blank(40,i=>[`CL-${String(i).padStart(3,'0')}`,d.close[(i-1)%8][0],d.close[(i-1)%8][1],d.close[(i-1)%8][2],'财务主管',null,'',d.close[(i-1)%8][3],i<=30?'是':'否','','未开始',null,'']),{A:12,B:10,C:42,D:18,E:15,F:16,G:24,H:34,I:13,J:30,K:11,L:14,M:13},'CloseTasks');s.getRange('F6:F45').format.numberFormat='yyyy-mm-dd hh:mm';s.getRange('L6:L45').format.numberFormat='yyyy-mm-dd';s.getRange('F6:M45').format.fill=amber;status(s.getRange('K6:K45'));
s=sheet(wb,'04-任务依赖关系','月结任务依赖关系','后续任务不得在前置任务未完成且影响重大时假装关闭。',['依赖编号','前置任务','后续任务','前置Owner','最迟完成','可否暂缓','暂缓条件','阻断处理','状态'],blank(30,i=>[`DEP-${String(i).padStart(3,'0')}`,'','','',null,'待判断','','','未开始']),{A:13,B:30,C:30,D:16,E:16,F:12,G:32,H:34,I:11},'Dependencies');s.getRange('E6:E35').format.numberFormat='yyyy-mm-dd hh:mm';s.getRange('B6:H35').format.fill=amber;status(s.getRange('I6:I35'));
s=sheet(wb,'05-主管复核Checklist','财务主管月度复核Checklist','不重复下属工作；按为什么、看什么、异常和Closure证据复核。',['编号','复核项目','为什么复核','看什么','异常标准','异常处理','Closure证据','本月结论','状态','复核人','复核日'],d.reviews.map((x,i)=>[`RV-${String(i+1).padStart(3,'0')}`,...x,'','未开始','',null]),{A:12,B:20,C:34,D:38,E:35,F:35,G:34,H:32,I:11,J:13,K:14},'ReviewChecklist');let re=5+d.reviews.length;s.getRange(`H6:K${re}`).format.fill=amber;s.getRange(`K6:K${re}`).format.numberFormat='yyyy-mm-dd';status(s.getRange(`I6:I${re}`));
s=sheet(wb,'06-Issue Log','财务问题管理台账 Issue Log','Resolved只代表动作完成；Closed必须验证账务、系统、资料、税务报表和控制。',['问题编号','发现日期','问题描述','流程','涉及科目','金额','风险等级','责任部门','责任人','财务Owner','根本原因','临时措施','永久措施','下一步','截止时间','升级状态','影响月结','影响税务','影响报表','完成日期','复核人','关闭状态','Closure证据','关闭日期'],blank(80,i=>[`ISS-${String(i).padStart(4,'0')}`,null,'','','',0,'黄色','','','','','','','',null,'未升级','待判断','待判断','待判断',null,'','Open','',null]),{A:13,B:14,C:36,D:16,E:18,F:15,G:13,H:16,I:14,J:14,K:30,L:30,M:30,N:30,O:16,P:16,Q:13,R:13,S:13,T:14,U:13,V:13,W:38,X:14},'IssueLog');s.getRange('B6:B85').format.numberFormat='yyyy-mm-dd';s.getRange('F6:F85').format.numberFormat='#,##0.00;[Red](#,##0.00);-';s.getRange('O6:O85').format.numberFormat='yyyy-mm-dd hh:mm';s.getRange('T6:T85').format.numberFormat='yyyy-mm-dd';s.getRange('X6:X85').format.numberFormat='yyyy-mm-dd';s.getRange('B6:X85').format.fill=amber;s.getRange('G6:G85').dataValidation={rule:{type:'list',values:['蓝色','黄色','橙色','红色']}};s.getRange('V6:V85').dataValidation={rule:{type:'list',values:['Open','In Progress','Pending','Resolved','Closed']}};
s=sheet(wb,'07-Action Plan','Action Plan','临时措施用于止损，永久措施用于消除根因。',['行动编号','关联Issue','行动事项','类型','Owner','开始日','截止日','完成标准','状态','实际完成日','复核人','证据'],blank(60,i=>[`ACT-${String(i).padStart(4,'0')}`,'','','永久/临时','',null,null,'','未开始',null,'','']),{A:13,B:14,C:34,D:13,E:14,F:14,G:14,H:38,I:11,J:14,K:13,L:38},'ActionPlan');s.getRange('F6:G65').format.numberFormat='yyyy-mm-dd';s.getRange('J6:J65').format.numberFormat='yyyy-mm-dd';s.getRange('B6:L65').format.fill=amber;status(s.getRange('I6:I65'));
s=sheet(wb,'08-资料催收表','月结资料催收表','写清资料、金额范围、准确截止、影响和升级路径。',['编号','资料/事项','期间','提供部门','责任人','首次提醒','要求时间','最后催收','影响','升级对象','状态','收到日','证据路径'],blank(60,i=>[`REQ-${String(i).padStart(3,'0')}`,'','','','','',null,null,'','','未开始',null,'']),{A:12,B:30,C:12,D:16,E:14,F:30,G:16,H:16,I:32,J:18,K:11,L:14,M:42},'RequestLog');s.getRange('G6:H65').format.numberFormat='yyyy-mm-dd hh:mm';s.getRange('L6:L65').format.numberFormat='yyyy-mm-dd';s.getRange('B6:M65').format.fill=amber;status(s.getRange('K6:K65'));
s=sheet(wb,'09-问题升级矩阵','财务问题升级矩阵','按金额、时间、法律税务、报表、现金和持续拖延综合判断。',['维度','一般','重要','重大/紧急','业务负责人','财务主管','财务经理','CFO/总经理','法务/外部专家'],[['金额','低于部门阈值','超过主管阈值','超过CFO阈值或资金安全','R','A','C/A','I/A','C'],['时间','不影响关键路径','可能影响月结','影响申报/出表/付款','R','A','A','I','C'],['法律税务','一般资料瑕疵','可能补税处罚','涉嫌违法或故意虚假','C','A','A','A','C/A'],['报表','不重大可量化','重大可修复','重大且无法可靠量化','C','A','A','A','C'],['现金','常规已授权','大额/异常','被骗、冻结、陌生账户','R','A','A','A','C'],['持续拖延','首次','连续两次','部门负责人仍不处理','R','A','A','I/A','-']],{A:16,B:28,C:28,D:32,E:16,F:16,G:16,H:18,I:20},'EscalationMatrix');
s=sheet(wb,'10-审批权限矩阵','财务审批权限矩阵','金额区间为企业自定义示例，不能当作统一行业标准。',['业务类型','低金额示例','中金额示例','高金额示例','异常/高风险','申请','部门审批','财务复核','最终批准','系统控制'],[['普通办公费','部门主管','部门负责人','总经理','异常用途提高层级','员工','部门','AP抽查','按额度','预算+发票'],['资本性支出','部门负责人','财务经理','CFO/总经理','未预算需例外','使用部门','部门负责人','资产/总账','按额度','预算+验收'],['预付款','采购负责人','财务经理','CFO','陌生供应商强化','采购','采购负责人','AP/资金','按额度','合同+账户核验'],['关联方','不因金额降低','财务经理','CFO/治理层','全部识别披露','业务','部门负责人','总账/税务','治理层规则','关联方标记'],['异常付款','例外审批','财务经理','CFO','涉嫌违法拒绝','业务','部门负责人','主管','CFO','限时例外'],['资产处置','资产负责人','财务经理','总经理','关联方/低价强化','使用部门','归口部门','资产会计','按额度','评估+处置审批']],{A:20,B:20,C:20,D:20,E:30,F:16,G:18,H:18,I:20,J:28},'ApprovalMatrix');
s=sheet(wb,'11-ERP权限矩阵','ERP权限与职责分离矩阵','记录角色冲突和补偿控制；禁止在表中记录密码。',['用户/角色','供应商主数据','凭证录入','凭证审核','付款制单','银行复核','反结账','系统管理','冲突说明','补偿控制','复核人','状态'],blank(40,i=>['','','','','','','','','','','','未开始']),{A:20,B:16,C:14,D:14,E:14,F:14,G:14,H:14,I:34,J:36,K:14,L:11},'ERPAccess');s.getRange('A6:K45').format.fill=amber;for(const c of ['B','C','D','E','F','G','H'])s.getRange(`${c}6:${c}45`).dataValidation={rule:{type:'list',values:['无','查询','录入','审核','管理员']}};status(s.getRange('L6:L45'));
s=sheet(wb,'12-重大会计事项跟踪','重大会计事项跟踪','判断复杂或影响重大时形成Accounting Memo。',['事项编号','事项','Fact状态','合同资料','适用准则','备选方案','建议方案','报表影响','税务影响','Owner','审批人','截止日','Memo编号','状态'],blank(40,i=>[`MAT-${String(i).padStart(3,'0')}`,'','待确认','','','','','','','','',null,'','未开始']),{A:13,B:32,C:14,D:28,E:28,F:38,G:34,H:28,I:28,J:14,K:14,L:14,M:16,N:11},'AccountingTopics');s.getRange('B6:M45').format.fill=amber;s.getRange('L6:L45').format.numberFormat='yyyy-mm-dd';status(s.getRange('N6:N45'));
s=sheet(wb,'13-Accounting Memo清单','Accounting Memo清单','Memo记录事实、规则、方案、影响、建议和批准；不是把结论倒写。',['Memo编号','事项背景','关键事实','会计问题','适用准则','分析','备选方案','建议','报表影响','税务影响','编制人','复核人','批准人','状态','文件路径'],blank(30,i=>[`MEMO-${String(i).padStart(3,'0')}`,'','','','','','','','','','','','','草稿','']),{A:15,B:34,C:36,D:28,E:28,F:44,G:38,H:34,I:28,J:28,K:13,L:13,M:13,N:11,O:46},'MemoRegister');s.getRange('B6:O35').format.fill=amber;s.getRange('N6:N35').dataValidation={rule:{type:'list',values:['草稿','待复核','待批准','已批准','已归档']}};
s=sheet(wb,'14-财务团队工作分配','财务团队工作分配表','管理容量、主备岗、频率、截止和完成证据。',['任务编号','任务','主岗','备岗','频率','计划工时','截止','完成证据','风险','本期状态','备注'],blank(50,i=>[`WK-${String(i).padStart(3,'0')}`,'','','','','',null,'','','未开始','']),{A:12,B:32,C:14,D:14,E:13,F:13,G:16,H:34,I:24,J:11,K:30},'WorkAllocation');s.getRange('B6:K55').format.fill=amber;s.getRange('G6:G55').format.numberFormat='yyyy-mm-dd hh:mm';status(s.getRange('J6:J55'));
s=sheet(wb,'15-周会Action List','财务团队周会Action List','只记录需决策、逾期、风险和跨部门行动，不记录流水账。',['行动编号','会议日期','事项','决策/下一步','Owner','截止日','风险','是否升级','状态','完成证据'],blank(50,i=>[`MTG-${String(i).padStart(3,'0')}`,null,'','','',null,'','否','未开始','']),{A:13,B:14,C:34,D:38,E:14,F:14,G:28,H:13,I:11,J:38},'WeeklyActions');s.getRange('B6:B55').format.numberFormat='yyyy-mm-dd';s.getRange('F6:F55').format.numberFormat='yyyy-mm-dd';s.getRange('B6:J55').format.fill=amber;status(s.getRange('I6:I55'));
const annual=[['每日','资金余额、重大付款、紧急Issue','主管决策/升级'],['每周','回款、挂账、付款计划、Action','周会清单'],['月末','Close、成本、税务、报表','月结包'],['季度','盘点、所得税预缴、权限复核','季度复核包'],['半年度','减值、重大合同、备岗演练','专项Memo'],['年度','预算、审计、汇算清缴、盘点','年度项目计划']];s=sheet(wb,'16-年度财务日历','年度财务工作日历','按高频、低频和重大专项安排主管精力。',['周期','重点事项','输出','责任人','计划日期','状态'],annual.map(x=>[...x,'财务主管',null,'未开始']),{A:14,B:45,C:34,D:16,E:16,F:11},'AnnualCalendar');s.getRange('E6:E11').format.numberFormat='yyyy-mm-dd';status(s.getRange('F6:F11'));
s=sheet(wb,'17-岗位Definition of Done','岗位完成标准 Definition of Done','“已做”需要结果、对账、异常和证据共同成立。',['岗位','任务','完成标准','必须证据','异常需升级','主管抽查','状态'],[['AP','应付月结','发票、暂估、AP/GL、异常和付款状态均清晰','核对表、暂估账龄、重复检查','重大借方/异常账户/重复付款','抽高风险供应商','未开始'],['AR','应收月结','开票、收入、收款、核销和账龄闭环','AR/GL、未认领、账龄','重大逾期/提前收入/异常退款','抽期末交易','未开始'],['成本','成本月结','工单、在制、分配、差异和GL一致','运行日志、差异桥、毛利分析','负库存/BOM/毛利突变','抽关键产品','未开始'],['税务','税务申报','账票税、申报、缴款和归档闭环','桥接表、回执、完税','销项遗漏/异常税率/逾期','复核差异和回执','未开始'],['总账','报表月结','模块对账、调整、重分类、勾稽、锁账','月结包、调整表、报表','重大未决/无法量化','复核重大和异常','未开始']],{A:13,B:20,C:40,D:34,E:34,F:26,G:11},'DefinitionDone');status(s.getRange('G6:G10'));
wb.recalculate();const err=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'formula error scan'});await fs.writeFile(`${qa}/errors.ndjson`,err.ndjson??String(err));const ins=await wb.inspect({kind:'table',range:'00-主管管理看板!A1:D14',include:'values,formulas',tableMaxRows:20,tableMaxCols:8});await fs.writeFile(`${qa}/inspect.ndjson`,ins.ndjson??String(ins));
const names=d.toolsheets;for(const n of names){const b=await wb.render({sheetName:n,autoCrop:'all',scale:0.65,format:'png'});await fs.writeFile(`${qa}/${n}.png`,new Uint8Array(await b.arrayBuffer()))}const file=await SpreadsheetFile.exportXlsx(wb);await file.save(`${out}/财务主管管理工具包.xlsx`);console.log(JSON.stringify({sheets:names.length,file:`${out}/财务主管管理工具包.xlsx`},null,2));
