import fs from 'node:fs/promises';
import { SpreadsheetFile, Workbook } from '@oai/artifact-tool';
const base=new URL('./',import.meta.url).pathname.slice(1), out=`${base}deliverables`, qa=`${base}qa_sheets`;
await fs.mkdir(out,{recursive:true}); await fs.mkdir(qa,{recursive:true});
const d=JSON.parse(await fs.readFile(`${base}content.json`,'utf8'));
const navy='#17365D', blue='#2F75B5', pale='#EAF2F8', gray='#F3F6F9', amber='#FFF2CC', green='#E2F0D9', red='#FCE4D6', line='#D9E1E8', font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function title(sh,t,sub,n){sh.showGridLines=false;sh.getRange(`A1:${col(n)}1`).merge();sh.getRange('A1').values=[[t]];sh.getRange('A1').format={font:{name:font,size:16,bold:true},rowHeight:30};sh.getRange(`A2:${col(n)}2`).merge();sh.getRange('A2').values=[[sub]];sh.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},rowHeight:25,wrapText:true};}
function header(sh,a){sh.getRange(a).format={fill:navy,font:{name:font,size:8,bold:true,color:'#FFFFFF'},horizontalAlignment:'center',verticalAlignment:'center',wrapText:true,rowHeight:35,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}
function body(sh,a,size=8){sh.getRange(a).format={font:{name:font,size:Math.round(size)},verticalAlignment:'center',wrapText:true,borders:{preset:'all',style:'thin',color:line}}}
function widths(sh,m){for(const [c,w] of Object.entries(m))sh.getRange(`${c}:${c}`).format.columnWidth=w}
function status(r,vals=['未开始','进行中','待复核','已完成','不适用']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{color:'#548235',bold:true}}});r.conditionalFormats.add('containsText',{text:'未开始',format:{fill:amber,font:{color:'#9C6500'}}});r.conditionalFormats.add('containsText',{text:'异常',format:{fill:red,font:{color:'#C00000',bold:true}}});}
function tableSheet(wb,name,t,sub,heads,rows,wmap,tname){const sh=wb.worksheets.add(name);title(sh,t,sub,heads.length);sh.getRange(`A5:${col(heads.length)}5`).values=[heads];header(sh,`A5:${col(heads.length)}5`);if(rows.length){sh.getRange(`A6:${col(heads.length)}${rows.length+5}`).values=rows;body(sh,`A6:${col(heads.length)}${rows.length+5}`);sh.tables.add(`A5:${col(heads.length)}${rows.length+5}`,true,tname).style='TableStyleMedium2'}widths(sh,wmap);sh.freezePanes.freezeRows(5);sh.freezePanes.freezeColumns(2);return sh}

// Workbook 1: 月结底稿模板包
const w1=Workbook.create();
const s0=w1.worksheets.add('00-使用说明与月结看板'); title(s0,'总账会计月结底稿模板包','黄色单元格为输入区；差异和逾期项目自动提示。金额单位由企业统一设定。版本日期：2026-09-10',10);
s0.getRange('A5:D5').values=[['指标','当前值','目标','使用说明']];header(s0,'A5:D5');s0.getRange('A6:A12').values=[['月结任务数'],['已完成'],['逾期未完成'],['对账差异总额'],['未决事项数'],['待主管复核'],['月结完成率']];s0.getRange('B6:B12').formulas=[["=COUNTA('01-月结Checklist'!A6:A35)"],["=COUNTIF('01-月结Checklist'!I6:I35,\"已完成\")"],["=COUNTIFS('01-月结Checklist'!I6:I35,\"<>已完成\",'01-月结Checklist'!E6:E35,\"<\"&TODAY())"],["=ABS('02-银行账户与余额调节'!H6)+ABS('02-银行账户与余额调节'!H7)+ABS('02-银行账户与余额调节'!H8)+ABS('02-银行账户与余额调节'!H9)+ABS('02-银行账户与余额调节'!H10)+ABS('02-银行账户与余额调节'!H11)+ABS('02-银行账户与余额调节'!H12)+ABS('02-银行账户与余额调节'!H13)+ABS('02-银行账户与余额调节'!H14)+ABS('02-银行账户与余额调节'!H15)+ABS('02-银行账户与余额调节'!H16)+ABS('02-银行账户与余额调节'!H17)+ABS('02-银行账户与余额调节'!H18)+ABS('02-银行账户与余额调节'!H19)+ABS('02-银行账户与余额调节'!H20)+ABS('02-银行账户与余额调节'!H21)+ABS('02-银行账户与余额调节'!H22)+ABS('02-银行账户与余额调节'!H23)+ABS('02-银行账户与余额调节'!H24)+ABS('02-银行账户与余额调节'!H25)+ABS('03-AR与GL核对'!F6)+ABS('03-AR与GL核对'!F7)+ABS('03-AR与GL核对'!F8)+ABS('03-AR与GL核对'!F9)+ABS('03-AR与GL核对'!F10)+ABS('03-AR与GL核对'!F11)+ABS('03-AR与GL核对'!F12)+ABS('03-AR与GL核对'!F13)+ABS('03-AR与GL核对'!F14)+ABS('03-AR与GL核对'!F15)+ABS('03-AR与GL核对'!F16)+ABS('03-AR与GL核对'!F17)+ABS('03-AR与GL核对'!F18)+ABS('03-AR与GL核对'!F19)+ABS('03-AR与GL核对'!F20)+ABS('03-AR与GL核对'!F21)+ABS('03-AR与GL核对'!F22)+ABS('03-AR与GL核对'!F23)+ABS('03-AR与GL核对'!F24)+ABS('03-AR与GL核对'!F25)+ABS('04-AP与GL核对'!F6)+ABS('04-AP与GL核对'!F7)+ABS('04-AP与GL核对'!F8)+ABS('04-AP与GL核对'!F9)+ABS('04-AP与GL核对'!F10)+ABS('04-AP与GL核对'!F11)+ABS('04-AP与GL核对'!F12)+ABS('04-AP与GL核对'!F13)+ABS('04-AP与GL核对'!F14)+ABS('04-AP与GL核对'!F15)+ABS('04-AP与GL核对'!F16)+ABS('04-AP与GL核对'!F17)+ABS('04-AP与GL核对'!F18)+ABS('04-AP与GL核对'!F19)+ABS('04-AP与GL核对'!F20)+ABS('04-AP与GL核对'!F21)+ABS('04-AP与GL核对'!F22)+ABS('04-AP与GL核对'!F23)+ABS('04-AP与GL核对'!F24)+ABS('04-AP与GL核对'!F25)"],["=COUNTIF('18-未决事项与主管复核'!K6:K45,\"<>已关闭\")"],["=COUNTIF('18-未决事项与主管复核'!K6:K45,\"待复核\")"],["=IF(B6=0,0,B7/B6)"]];s0.getRange('C6:C12').values=[[30],[30],[0],[0],[0],[0],[1]];s0.getRange('D6:D12').values=[['来源于月结Checklist'],['状态选择已完成'],['截止日早于今天且未完成'],['银行、AR和AP示例差异绝对值'],['未决事项状态未关闭'],['主管应查看证据和结论'],['已完成/任务数']];body(s0,'A6:D12');s0.getRange('B12:C12').format.numberFormat='0%';widths(s0,{A:24,B:16,C:14,D:46});s0.freezePanes.freezeRows(5);
const checklist=Array.from({length:30},(_,i)=>[`CL-${String(i+1).padStart(2,'0')}`,['业务截止','接口检查','资金','AP','AR','库存','成本','固定资产','薪酬','税务','GL','报表'][i%12],['确认业务单据截止','检查接口批次','完成银行调节','核对应付和暂估','核对应收和收入','锁定库存并盘点','运行成本并分析差异','运行折旧并核对卡片','工资接口及个税核对','账票税勾稽','调整分录及损益结转','报表勾稽和版本锁定'][i%12],['业务','IT','资金','AP','AR','仓库','成本','资产','薪酬','税务','总账','财务主管'][i%12],null,'月度','系统报表/底稿/审批记录','是','未开始','','']);
let sh=tableSheet(w1,'01-月结Checklist','月结Checklist','先定义截止和依赖，再按证据关闭任务。',['编号','阶段','任务','责任人','截止日期','频率','完成证据','是否阻断','状态','异常说明','复核人'],checklist,{A:10,B:14,C:35,D:13,E:14,F:10,G:32,H:12,I:11,J:30,K:13},'CloseChecklist');sh.getRange('E6:E35').format.numberFormat='yyyy-mm-dd';status(sh.getRange('I6:I35'));
function blankRows(n,make){return Array.from({length:n},(_,i)=>make(i+1))}
sh=tableSheet(w1,'02-银行账户与余额调节','银行余额调节表','账面余额与银行对账单余额通过未达项调节至一致。',['账户编号','开户行','账号后四位','币种','账面余额','银行余额','未达调整净额','调节后差异','未达事项','责任人','状态'],blankRows(20,i=>[`BA-${String(i).padStart(2,'0')}`,'','','CNY',0,0,0,null,'','','未开始']),{A:12,B:20,C:12,D:9,E:15,F:15,G:16,H:15,I:32,J:13,K:11},'BankRecon');sh.getRange('H6:H25').formulas=blankRows(20,i=>[`=E${i+5}+G${i+5}-F${i+5}`]);sh.getRange('E6:H25').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('E6:G25').format.fill=amber;status(sh.getRange('K6:K25'));
function reconSheet(name,titleText,prefix){let s=tableSheet(w1,name,titleText,'先统一公司、币种、截止日、过账状态和科目范围。',['对象编号','对象名称','子模块余额','总账余额','调整项目','差异','差异原因','处理方案','责任人','状态'],blankRows(20,i=>[`${prefix}-${String(i).padStart(3,'0')}`,'',0,0,0,null,'','','','未开始']),{A:14,B:24,C:16,D:16,E:15,F:15,G:30,H:30,I:13,J:11},prefix+'Recon');s.getRange('F6:F25').formulas=blankRows(20,i=>[`=C${i+5}+E${i+5}-D${i+5}`]);s.getRange('C6:F25').format.numberFormat='#,##0.00;[Red](#,##0.00);-';s.getRange('C6:E25').format.fill=amber;status(s.getRange('J6:J25'));return s}
reconSheet('03-AR与GL核对','应收子模块与总账核对','AR'); reconSheet('04-AP与GL核对','应付子模块与总账核对','AP');
sh=tableSheet(w1,'05-暂估台账','暂估台账','货到/服务已发生未收票；逐项跟踪到票、冲销和价差。',['编号','供应商','业务/PO','收货/验收日','不含税暂估','已到票金额','未到票余额','账龄天数','价差','下步动作','责任人','状态'],blankRows(40,i=>[`AC-${String(i).padStart(3,'0')}`,'','',null,0,0,null,null,0,'','','未开始']),{A:12,B:22,C:18,D:14,E:16,F:16,G:16,H:12,I:14,J:28,K:13,L:11},'AccrualLog');sh.getRange('G6:G45').formulas=blankRows(40,i=>[`=E${i+5}-F${i+5}`]);sh.getRange('H6:H45').formulas=blankRows(40,i=>[`=IF(D${i+5}="","",TODAY()-D${i+5})`]);sh.getRange('D6:D45').format.numberFormat='yyyy-mm-dd';sh.getRange('E6:G45').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('D6:F45').format.fill=amber;status(sh.getRange('L6:L45'));
function timingSheet(name,titleText,prefix){let s=tableSheet(w1,name,titleText,'黄色列为业务输入；余额和摊销/冲回由公式辅助检查。',['编号','事项','部门/供应商','开始日','结束日','总金额','以前确认','本月应确认','期末余额','科目','依据','状态'],blankRows(30,i=>[`${prefix}-${String(i).padStart(3,'0')}`,'','',null,null,0,0,0,null,'','','未开始']),{A:12,B:24,C:20,D:13,E:13,F:15,G:15,H:15,I:15,J:18,K:28,L:11},prefix+'Timing');s.getRange('I6:I35').formulas=blankRows(30,i=>[`=F${i+5}-G${i+5}-H${i+5}`]);s.getRange('D6:E35').format.numberFormat='yyyy-mm-dd';s.getRange('F6:I35').format.numberFormat='#,##0.00;[Red](#,##0.00);-';s.getRange('B6:H35').format.fill=amber;status(s.getRange('L6:L35'));return s}
timingSheet('06-预提费用','预提费用底稿','PR'); timingSheet('07-待摊长期待摊','待摊与长期待摊底稿','PP');
sh=tableSheet(w1,'08-应收应付账龄','往来账龄分析','到期日优先；没有到期日时以凭证/发票日替代并注明。',['类型','对象','单据号','业务日期','到期日','余额','未到期','1-30天','31-60天','61-90天','90天以上','责任人','状态'],blankRows(50,i=>[i%2?'应收':'应付','','',null,null,0,null,null,null,null,null,'','未开始']),{A:10,B:22,C:18,D:13,E:13,F:15,G:14,H:14,I:14,J:14,K:15,L:13,M:11},'Aging');for(let r=6;r<=55;r++){sh.getRange(`G${r}`).formulas=[[`=IF(E${r}="",0,IF(TODAY()<=E${r},F${r},0))`]];sh.getRange(`H${r}`).formulas=[[`=IF(E${r}="",0,IF(AND(TODAY()-E${r}>=1,TODAY()-E${r}<=30),F${r},0))`]];sh.getRange(`I${r}`).formulas=[[`=IF(E${r}="",0,IF(AND(TODAY()-E${r}>=31,TODAY()-E${r}<=60),F${r},0))`]];sh.getRange(`J${r}`).formulas=[[`=IF(E${r}="",0,IF(AND(TODAY()-E${r}>=61,TODAY()-E${r}<=90),F${r},0))`]];sh.getRange(`K${r}`).formulas=[[`=IF(E${r}="",0,IF(TODAY()-E${r}>90,F${r},0))`]];}sh.getRange('D6:E55').format.numberFormat='yyyy-mm-dd';sh.getRange('F6:K55').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('A6:F55').format.fill=amber;status(sh.getRange('M6:M55'));
function issueSheet(name,t,prefix){let s=tableSheet(w1,name,t,'重大、逾期或长期未清事项需要责任人、期限和关闭证据。',['编号','对象/人员','事项','发生日','金额','账龄天数','原因','处理动作','期限','责任人','关闭证据','状态'],blankRows(40,i=>[`${prefix}-${String(i).padStart(3,'0')}`,'','',null,0,null,'','',null,'','','未开始']),{A:12,B:20,C:28,D:13,E:15,F:12,G:28,H:30,I:13,J:13,K:28,L:11},prefix+'Issues');s.getRange('F6:F45').formulas=blankRows(40,i=>[`=IF(D${i+5}="","",TODAY()-D${i+5})`]);s.getRange('D6:D45').format.numberFormat='yyyy-mm-dd';s.getRange('I6:I45').format.numberFormat='yyyy-mm-dd';s.getRange('D6:E45').format.fill=amber;status(s.getRange('L6:L45'));return s}
issueSheet('09-长期挂账','长期挂账清理','LT'); issueSheet('10-员工借款','员工借款与备用金','EA'); issueSheet('11-关联方往来','关联方往来核对','RP');
function controlSheet(name,t,items,prefix){return tableSheet(w1,name,t,'记录来源、账面数、业务数和差异结论。',['编号','检查项目','数据来源','业务/模块金额','总账金额','差异','差异解释','调整凭证','责任人','状态'],items.map((x,i)=>[`${prefix}-${String(i+1).padStart(2,'0')}`,x,'',0,0,null,'','','','未开始']),{A:12,B:30,C:26,D:16,E:16,F:15,G:32,H:18,I:13,J:11},prefix+'Control')}
for(const [name,t,items,p] of [['12-存货与成本检查','存货与成本检查',['收发存与GL','负库存','零成本出库','工单在制','制造费用分配','成本差异','盘点差异','跌价准备'],'IC'],['13-固定资产与在建工程','固定资产与在建工程',['卡片与GL','本月新增','在建转固','折旧运行','资产处置','闲置减值','盘点差异'],'FA'],['14-薪酬核对','薪酬完整核对',['HR人数','工资总额','银行实发','个税申报','社保公积金','费用归属','离职人员'],'PY'],['15-税务资料包','税务资料包',['销项与收入','进项与勾选','增值税申报','附加税','企业所得税','个税','印花税','缴税回单'],'TX']]){let s=controlSheet(name,t,items,p);let end=5+items.length;s.getRange(`F6:F${end}`).formulas=items.map((x,i)=>[`=D${i+6}-E${i+6}`]);s.getRange(`D6:E${end}`).format.fill=amber;s.getRange(`D6:F${end}`).format.numberFormat='#,##0.00;[Red](#,##0.00);-';status(s.getRange(`J6:J${end}`));}
sh=tableSheet(w1,'16-调整分录','调整分录清单','账错应做凭证；账没错仅列报不当的事项进入报表重分类表。',['编号','原因','借方科目','借方金额','贷方科目','贷方金额','凭证号','是否过账','税务影响','编制人','复核人','状态'],blankRows(40,i=>[`JE-${String(i).padStart(3,'0')}`,'','',0,'',0,'','否','','','','未开始']),{A:12,B:30,C:22,D:15,E:22,F:15,G:16,H:12,I:24,J:13,K:13,L:11},'Adjustments');sh.getRange('D6:F45').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('B6:I45').format.fill=amber;status(sh.getRange('L6:L45'));
sh=tableSheet(w1,'17-报表重分类','报表重分类清单','仅列报层调整，不改变总账；必须记录报表项目、金额和抵销关系。',['编号','事项','原列报项目','调整金额','调整后项目','报表','原因','是否影响账','编制人','复核人','状态'],blankRows(30,i=>[`RC-${String(i).padStart(3,'0')}`,'','',0,'','','','否','','','未开始']),{A:12,B:28,C:24,D:16,E:24,F:14,G:32,H:13,I:13,J:13,K:11},'Reclasses');sh.getRange('D6:D35').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('B6:H35').format.fill=amber;status(sh.getRange('K6:K35'));
sh=tableSheet(w1,'18-未决事项与主管复核','未决事项与主管复核','月结关闭不等于问题消失；重大事项应明确是否阻断、谁批准带入下月。',['编号','事项','金额','报表影响','税务影响','是否阻断月结','处理方案','责任人','截止日期','主管结论','状态','关闭日期'],blankRows(40,i=>[`OI-${String(i).padStart(3,'0')}`,'',0,'','','待判断','','',null,'','未开始',null]),{A:12,B:30,C:15,D:24,E:24,F:15,G:32,H:13,I:14,J:32,K:11,L:14},'OpenItems');sh.getRange('C6:C45').format.numberFormat='#,##0.00;[Red](#,##0.00);-';sh.getRange('I6:I45').format.numberFormat='yyyy-mm-dd';sh.getRange('L6:L45').format.numberFormat='yyyy-mm-dd';sh.getRange('B6:J45').format.fill=amber;status(sh.getRange('K6:K45'),['未开始','进行中','待复核','已关闭']);
w1.recalculate();

// Workbook 2: 资料与交接工具
const w2=Workbook.create();
let s=w2.worksheets.add('00-使用说明与资料看板');title(s,'财务资料与岗位交接工具包','用于资料盘点、催收、索引、权限和交接；避免把敏感密码直接写入表格。版本日期：2026-09-10',10);s.getRange('A5:D5').values=[['指标','当前值','目标','说明']];header(s,'A5:D5');s.getRange('A6:A12').values=[['资料项目'],['已完成资料'],['逾期资料'],['未决事项'],['待回收权限'],['交接问题数'],['交接完成率']];s.getRange('B6:B12').formulas=[["=COUNTA('01-财务资料总清单'!A6:A100)"],["=COUNTIF('01-财务资料总清单'!S6:S100,\"已完成\")"],["=COUNTIFS('03-资料催收表'!J6:J65,\"<>已完成\",'03-资料催收表'!F6:F65,\"<\"&TODAY())"],["=COUNTIF('11-未决事项'!K6:K65,\"<>已关闭\")"],["=COUNTIFS('07-系统及权限清单'!J6:J55,\"离职/转岗\",'07-系统及权限清单'!K6:K55,\"否\")"],["=COUNTA('15-100个交接问题'!A6:A105)"],["=IF(B6=0,0,B7/B6)"]];s.getRange('C6:C12').values=[[d.materials.length],[d.materials.length],[0],[0],[0],[100],[1]];s.getRange('D6:D12').values=[['来源于资料总清单'],['状态已完成'],['已过期限仍未完成'],['需责任人和关闭证据'],['禁止共享账号和明文密码'],['按十类问题现场验证'],['已完成/资料项目']];body(s,'A6:D12');s.getRange('B12:C12').format.numberFormat='0%';widths(s,{A:24,B:16,C:14,D:48});
const mh=['编号','资料类别','资料名称','业务循环','用途','来源系统','提供部门','维护人','工具','更新频率','月结用途','预计耗时','ERP覆盖','Excel建议','保存路径','保管口径','敏感级别','复核人','状态'];
s=tableSheet(w2,'01-财务资料总清单','财务资料总清单','每项资料明确来源、责任、频率、保存和复核。',mh,d.materials.map((m,i)=>[`MAT-${String(i+1).padStart(3,'0')}`,m.category,m.name,m.cycle,m.use,m.source,m.provider,m.owner,m.tool,m.frequency,m.month,m.time,m.erp,m.excel,m.save,m.retention,m.sensitive,m.reviewer,'未开始']),{A:12,B:18,C:24,D:18,E:36,F:22,G:18,H:14,I:22,J:18,K:38,L:14,M:13,N:36,O:42,P:28,Q:13,R:18,S:11},'MaterialMaster');status(s.getRange(`S6:S${5+d.materials.length}`));
s=tableSheet(w2,'02-资料整理时间表','资料整理时间表','按形成、复核、归档和自动化改造分解时间投入。',['工作阶段','预计耗时','工作量','完成证据','自动化建议'],d.time_map,{A:22,B:15,C:12,D:42,E:46},'TimeMap');
s=tableSheet(w2,'03-资料催收表','资料催收表','催收应写清对象、金额/范围、截止日和未交后果。',['编号','资料','期间','提供人','首次通知日','要求日期','最近催收日','影响','升级对象','状态','实际收到日','备注'],blankRows(60,i=>[`RQ-${String(i).padStart(3,'0')}`,'','','',null,null,null,'','','未开始',null,'']),{A:12,B:28,C:12,D:15,E:14,F:14,G:14,H:32,I:16,J:11,K:14,L:30},'RequestLog');s.getRange('E6:G65').format.numberFormat='yyyy-mm-dd';s.getRange('K6:K65').format.numberFormat='yyyy-mm-dd';s.getRange('B6:I65').format.fill=amber;status(s.getRange('J6:J65'));
s=tableSheet(w2,'04-T5至T2月结日历','T-5至T+2月结日历','用相对日期适配每月自然日、周末和节假日。',['相对日','关键动作','对象','输出','未完成处理'],d.chase,{A:12,B:45,C:28,D:36,E:38},'CloseCalendar');
s=tableSheet(w2,'05-文件索引','财务文件索引','每个正式文件分配唯一ID；记录路径、版本、权限和保管。',['文件ID','文件名','类别','期间','公司','当前版本','状态','责任人','复核人','完整路径','敏感级别','保管期限','最后更新日','备注'],blankRows(80,i=>[`FILE-${String(i).padStart(4,'0')}`,'','','','','v0.1','草稿','','','','内部','','','']),{A:14,B:36,C:18,D:12,E:18,F:12,G:11,H:13,I:13,J:52,K:13,L:20,M:14,N:28},'FileIndex');s.getRange('M6:M85').format.numberFormat='yyyy-mm-dd';s.getRange('B6:M85').format.fill=amber;
s=tableSheet(w2,'06-版本管理','版本变更记录','锁定版本后不得覆盖；任何修改都登记原因、影响和批准人。',['文件ID','版本','变更日期','变更人','变更内容','影响金额/范围','原因','复核人','批准人','旧版路径','新版路径','状态'],blankRows(60,i=>['','v0.1',null,'','','','','','','','','草稿']),{A:14,B:10,C:14,D:13,E:32,F:20,G:28,H:13,I:13,J:45,K:45,L:11},'VersionLog');s.getRange('C6:C65').format.numberFormat='yyyy-mm-dd';s.getRange('A6:K65').format.fill=amber;
s=tableSheet(w2,'07-系统及权限清单','系统与权限清单','只记录账号和角色，不记录密码。离职或转岗及时回收。',['编号','系统','用户','部门','角色','关键权限','授权日期','审批人','最近复核日','人员状态','是否已回收','回收日期','备注'],blankRows(50,i=>[`AUTH-${String(i).padStart(3,'0')}`,'','','','','',null,'',null,'在职','否',null,'']),{A:13,B:20,C:16,D:15,E:22,F:32,G:14,H:14,I:14,J:12,K:13,L:14,M:28},'AccessList');s.getRange('G6:G55').format.numberFormat='yyyy-mm-dd';s.getRange('I6:I55').format.numberFormat='yyyy-mm-dd';s.getRange('L6:L55').format.numberFormat='yyyy-mm-dd';s.getRange('B6:M55').format.fill=amber;
s=tableSheet(w2,'08-银行账户与网银权限','银行账户与网银权限','U盾编号可记录；密码、动态码不得记录。',['账户编号','开户行','户名','账号后四位','币种','用途','状态','网银角色','持有人','U盾编号','授权限额','最近复核日','回收状态'],blankRows(30,i=>[`BANK-${String(i).padStart(3,'0')}`,'','','','CNY','','正常','','','',0,null,'不适用']),{A:13,B:22,C:20,D:13,E:9,F:24,G:11,H:18,I:14,J:16,K:15,L:14,M:13},'BankAccess');s.getRange('K6:K35').format.numberFormat='#,##0.00';s.getRange('L6:L35').format.numberFormat='yyyy-mm-dd';s.getRange('B6:M35').format.fill=amber;
s=tableSheet(w2,'09-税务信息清单','税务信息清单','记录税种、主管税务机关、申报周期、口径和责任；不保存账号密码。',['主体','纳税识别号','主管税务机关','税种','纳税人资格','申报周期','申报渠道','数据来源','责任人','复核人','最后申报期','未决问题'],blankRows(30,i=>['','','','','','月/季/年','','','','','','']),{A:20,B:22,C:22,D:16,E:18,F:13,G:20,H:32,I:13,J:13,K:14,L:32},'TaxInfo');s.getRange('A6:L35').format.fill=amber;
s=tableSheet(w2,'10-重大合同清单','重大合同清单','跟踪主体、金额、履约、开票、结算和关键会计税务条款。',['合同编号','对方','类型','签订日','含税金额','履约状态','开票状态','结算状态','会计关注','税务关注','责任部门','财务责任人','文件路径'],blankRows(50,i=>['','','',null,0,'未开始','未开票','未结算','','','','','']),{A:18,B:22,C:15,D:13,E:16,F:13,G:13,H:13,I:30,J:30,K:15,L:15,M:48},'MaterialContracts');s.getRange('D6:D55').format.numberFormat='yyyy-mm-dd';s.getRange('E6:E55').format.numberFormat='#,##0.00;[Red](#,##0.00);-';s.getRange('A6:M55').format.fill=amber;
s=tableSheet(w2,'11-未决事项','未决事项清单','金额、风险、责任、期限和关闭证据缺一不可。',['编号','事项','模块','金额','风险','当前结论','下一动作','责任人','截止日','升级对象','状态','关闭证据'],blankRows(60,i=>[`OPEN-${String(i).padStart(3,'0')}`,'','',0,'','','','',null,'','未开始','']),{A:13,B:30,C:16,D:15,E:28,F:32,G:32,H:13,I:14,J:16,K:11,L:30},'OpenIssueList');s.getRange('D6:D65').format.numberFormat='#,##0.00;[Red](#,##0.00);-';s.getRange('I6:I65').format.numberFormat='yyyy-mm-dd';s.getRange('B6:J65').format.fill=amber;status(s.getRange('K6:K65'),['未开始','进行中','待复核','已关闭']);
function checklistTool(name,t,items,prefix){let s=tableSheet(w2,name,t,'完成应有证据；接收不等于验证。',['编号','事项','应取得/完成','责任人','计划日','实际日','证据位置','状态','备注'],items.map((x,i)=>[`${prefix}-${String(i+1).padStart(3,'0')}`,x[0],x[1],'',null,null,'','未开始','']),{A:13,B:28,C:42,D:13,E:14,F:14,G:38,H:11,I:28},prefix+'Checklist');s.getRange(`E6:F${5+items.length}`).format.numberFormat='yyyy-mm-dd';s.getRange(`D6:G${5+items.length}`).format.fill=amber;status(s.getRange(`H6:H${5+items.length}`));return s}
checklistTool('12-入职第一周清单','入职第一周清单',[['组织和关账','组织图、岗位表、月结日历'],['系统和权限','成功登录并导出关键报表'],['账和台账','从TB追到明细和源单'],['银行和税务','复核一张银行调节和一项申报数字'],['未决事项','形成风险清单和30天行动计划'],['制度和口径','取得会计政策、制度和重大判断'],['档案路径','能定位上月月结包和年度档案'],['关键联系人','业务、IT、银行、税务和审计联系人']], 'ON');
checklistTool('13-岗位交接清单','岗位交接清单',d.ledger_specs.map(l=>[l[0],`${l[1]}；证据：${l[5]}`]),'HO');
checklistTool('14-离职交接清单','离职交接清单',[['确定基准日','锁定最后工作日和交接范围'],['文件归档','正式路径、版本和索引完整'],['余额和台账','关键余额已对账并解释'],['未决事项','责任人、期限和下步动作'],['系统权限','账号、角色和设备清单'],['银行权限','网银角色和U盾已移交/回收'],['税务身份','实名办税和授权已变更'],['现场演示','接任者重做关键月结任务'],['签字确认','交接人、接收人、监交人签字'],['观察期','确定答疑人和结束日期']], 'EXIT');
s=tableSheet(w2,'15-100个交接问题','100个核心交接问题','不要只记录口头答案；要求路径、报表、日志、合同或抽样重做作为证据。',['编号','类别','必须问的问题','为什么问','应取得证据','回答摘要','责任人','状态'],d.questions.map(q=>[q.id,q.category,q.question,q.why,q.evidence,'','',q.status]),{A:12,B:18,C:48,D:48,E:46,F:38,G:13,H:11},'HandoverQuestions');s.getRange('F6:H105').format.fill=amber;status(s.getRange('H6:H105'),['待询问','已回答','待验证','已验证','不适用']);
w2.recalculate();

async function exportBook(wb,file,prefix,sheets){
  const er=await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'formula scan'});await fs.writeFile(`${qa}/${prefix}_errors.ndjson`,er.ndjson??String(er));
  const ins=await wb.inspect({kind:'table',range:`${sheets[0]}!A1:J15`,include:'values,formulas',tableMaxRows:20,tableMaxCols:12});await fs.writeFile(`${qa}/${prefix}_inspect.ndjson`,ins.ndjson??String(ins));
  for(const n of sheets){const b=await wb.render({sheetName:n,autoCrop:'all',scale:0.65,format:'png'});await fs.writeFile(`${qa}/${prefix}_${n}.png`,new Uint8Array(await b.arrayBuffer()));}
  const f=await SpreadsheetFile.exportXlsx(wb);await f.save(`${out}/${file}`);
}
const s1=['00-使用说明与月结看板','01-月结Checklist','02-银行账户与余额调节','03-AR与GL核对','04-AP与GL核对','05-暂估台账','06-预提费用','07-待摊长期待摊','08-应收应付账龄','09-长期挂账','10-员工借款','11-关联方往来','12-存货与成本检查','13-固定资产与在建工程','14-薪酬核对','15-税务资料包','16-调整分录','17-报表重分类','18-未决事项与主管复核'];
const s2=['00-使用说明与资料看板','01-财务资料总清单','02-资料整理时间表','03-资料催收表','04-T5至T2月结日历','05-文件索引','06-版本管理','07-系统及权限清单','08-银行账户与网银权限','09-税务信息清单','10-重大合同清单','11-未决事项','12-入职第一周清单','13-岗位交接清单','14-离职交接清单','15-100个交接问题'];
await exportBook(w1,'总账会计月结底稿模板包.xlsx','close',s1);await exportBook(w2,'财务资料与岗位交接工具包.xlsx','handover',s2);
console.log(JSON.stringify({workbook1:s1.length,workbook2:s2.length,materials:d.materials.length,questions:d.questions.length},null,2));
