import fs from 'node:fs/promises'; import path from 'node:path'; import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';
const base=path.dirname(new URL(import.meta.url).pathname.slice(1)),out=path.join(base,'deliverables'),qa=path.join(base,'qa'); await fs.mkdir(out,{recursive:true}); await fs.mkdir(qa,{recursive:true}); const d=JSON.parse(await fs.readFile(path.join(base,'content.json'),'utf8'));
const nav='#17365D',yellow='#FFF2CC',green='#E2F0D9',red='#FCE4D6',line='#D9E2F3',font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function title(s,t,sub,n){s.showGridLines=false;s.getRange(`A1:${col(n)}1`).merge();s.getRange('A1').values=[[t]];s.getRange('A1').format={font:{name:font,size:16,bold:true},rowHeight:30};s.getRange(`A2:${col(n)}2`).merge();s.getRange('A2').values=[[sub]];s.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},wrapText:true,rowHeight:28}}
function head(s,a){s.getRange(a).format={fill:nav,font:{name:font,size:8,bold:true,color:'#FFFFFF'},wrapText:true,horizontalAlignment:'center',verticalAlignment:'center',rowHeight:34,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}
function body(s,a){s.getRange(a).format={font:{name:font,size:8},wrapText:true,verticalAlignment:'center',borders:{preset:'all',style:'thin',color:line}}}
function widths(s,m){for(const[k,v]of Object.entries(m))s.getRange(`${k}:${k}`).format.columnWidth=v}
function make(w,n,t,sub,h,rows,wm,tn){const s=w.worksheets.add(n);title(s,t,sub,h.length);s.getRange(`A5:${col(h.length)}5`).values=[h];head(s,`A5:${col(h.length)}5`);if(rows.length){s.getRange(`A6:${col(h.length)}${5+rows.length}`).values=rows;body(s,`A6:${col(h.length)}${5+rows.length}`);s.tables.add(`A5:${col(h.length)}${5+rows.length}`,true,tn).style='TableStyleMedium2'}widths(s,wm);s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(Math.min(3,h.length));return s}
function status(r,vals=['未开始','进行中','待复核','已完成']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{bold:true,color:'#548235'}}});r.conditionalFormats.add('containsText',{text:'高',format:{fill:red,font:{bold:true,color:'#C00000'}}})}
const w=Workbook.create(); let s;
// 00 dashboard
s=w.worksheets.add('00-管理看板');title(s,'企业存货管理工具包','案例企业：华辰智造科技有限公司。黄色单元格为人工维护，金额单位为元。',8);s.getRange('A5:D5').values=[['指标','本期结果','预警/目标','财务主管动作']];head(s,'A5:D5');s.getRange('A6:A18').values=[['库存总额'],['原材料及辅料'],['在产品'],['产成品/库存商品'],['发出/外仓/委外'],['负库存SKU数'],['负库存金额'],['>365天库存金额'],['呆滞/停产库存金额'],['存货周转率（年化）'],['存货周转天数'],['Open盘点差异'],['Open重大Issue']];s.getRange('B6:B18').formulas=[["=SUM('02-库存明细'!H6:H23)"],["=SUMIF('02-库存明细'!C6:C23,\"原材料\",'02-库存明细'!H6:H23)+SUMIF('02-库存明细'!C6:C23,\"辅料\",'02-库存明细'!H6:H23)+SUMIF('02-库存明细'!C6:C23,\"包装物\",'02-库存明细'!H6:H23)"],["=SUMIF('02-库存明细'!C6:C23,\"在产品\",'02-库存明细'!H6:H23)"],["=SUMIF('02-库存明细'!C6:C23,\"产成品\",'02-库存明细'!H6:H23)+SUMIF('02-库存明细'!C6:C23,\"库存商品\",'02-库存明细'!H6:H23)"],["=SUMIF('02-库存明细'!C6:C23,\"发出商品\",'02-库存明细'!H6:H23)+SUMIF('02-库存明细'!C6:C23,\"委托加工物资\",'02-库存明细'!H6:H23)"],["=COUNTIF('02-库存明细'!F6:F23,\"<0\")"],["=SUMIF('02-库存明细'!F6:F23,\"<0\",'02-库存明细'!H6:H23)"],["=SUMIF('02-库存明细'!J6:J23,\">365\",'02-库存明细'!H6:H23)"],["='02-库存明细'!H9+'02-库存明细'!H18"],[`=${d.company.cogs_ytd}/AVERAGE(${d.company.avg_inventory},${d.company.inventory_total})*12/8`],["=365/B15"],["=COUNTIF('12-盘点差异'!M6:M45,\"Open\")"],["=COUNTIF('24-Issue Log'!E6:E45,\"高\")"]];s.getRange('C6:C18').values=[['与GL一致'],['结构观察'],['重点<30天'],['结合销售'],['逐项外部证据'],[0],[0],[0],['逐项方案'],['同行/趋势'],['趋势下降'],[0],[0]];s.getRange('D6:D18').values=[['核对总账、模块、WMS'],['解释量价结构'],['查工序瓶颈和假报工'],['查滞销和订单取消'],['对账/函证/盘点'],['逐笔清理并关超发'],['评估毛利和期间'],['业务给使用/处置计划'],['NRV测算+Owner'],['分原料/WIP/成品'],['结合缺货率'],['证据、调账、追责、Closure'],['升级并验证临时控制']];body(s,'A6:D18');s.getRange('B6:B14').format.numberFormat='¥#,##0';s.getRange('B15').format.numberFormat='0.00x';s.getRange('B16').format.numberFormat='0.0';widths(s,{A:30,B:18,C:20,D:52});s.getRange('B11:B12').conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{fill:red,font:{color:'#C00000',bold:true}}});
// RACI
s=make(w,'01-RACI','存货管理岗位责任矩阵','R=执行/牵头，A=最终负责。财务负责核算、监督、复核和升级。',['事项','R执行/牵头','财务角色','A最终负责','主要风险'],d.raci.map(x=>[x[0],x[1],x[2],x[4],x[5]]),{A:34,B:34,C:25,D:22,E:45},'InvRACI');
// inventory detail
let rows=d.inventory.map(x=>[x[0],x[1],x[2],x[3],x[4],x[5],x[6],x[7],new Date(x[8]),x[9],x[10],x[11],'']);s=make(w,'02-库存明细','库存明细与责任台账','连接SKU、仓库、数量、单位成本、金额、库龄、状态和责任部门。',['物料编码','名称','类别','单位','仓库/库位','数量','单位成本','金额','最后移动日','库龄天数','状态','责任部门','处理计划'],rows,{A:16,B:26,C:18,D:10,E:26,F:14,G:14,H:16,I:15,J:12,K:16,L:15,M:46},'InventoryDetail');s.getRange('F6:H23').format.numberFormat='#,##0.00';s.getRange('I6:I23').format.numberFormat='yyyy-mm-dd';s.getRange('J6:J23').format.numberFormat='0';s.getRange('K6:M23').format.fill=yellow;s.getRange('F6:F23').conditionalFormats.add('cellIs',{operator:'lessThan',formula:0,format:{fill:red,font:{color:'#C00000',bold:true}}});
// master data
rows=d.inventory.map(x=>[x[0],x[1],x[2],x[3],'','',x[4].split('-')[0],x[4],x[10],'有效','','','']);s=make(w,'03-物料主数据','物料与SKU主数据检查','重点检查一物多码、一码多物、单位转换、版本、成本类和仓库库位。',['物料编码','名称','类别','基本单位','采购单位','转换系数','仓库','库位','状态/用途','主数据状态','重复/近似编码','最后审核日','复核意见'],rows,{A:16,B:26,C:18,D:12,E:12,F:13,G:14,H:24,I:18,J:15,K:30,L:15,M:42},'MasterData');s.getRange('E6:M23').format.fill=yellow;
// procurement match
rows=[['PO260801','RM-IC-001',20000,86,18000,86,18000,86,.13,'已匹配','',''],['PO260802','RM-LCD-004',5000,208,4200,210,5000,208,.13,'数量/价格差异','待采购说明',''],['PO260803','RM-CASE-003',8000,118,7200,118,0,0,.13,'未到票','月末暂估',''],...Array.from({length:37},(_,i)=>[`PO-${String(i+4).padStart(3,'0')}`,'',0,0,0,0,0,0,0,'','',''])];s=make(w,'04-三单匹配','PO-GR-Invoice三单匹配','按行比较物料、单位、数量、价格、税率和时间；超容差须调查。',['PO','物料','订单数量','订单单价','收货数量','收货单价','发票数量','发票单价','税率','匹配结果','处理','复核'],rows,{A:15,B:16,C:14,D:14,E:14,F:14,G:14,H:14,I:11,J:20,K:38,L:30},'ThreeWay');s.getRange('C6:H45').format.numberFormat='#,##0.00';s.getRange('I6:I45').format.numberFormat='0%';s.getRange('J6:L45').format.fill=yellow;
// receipt exceptions
let exc=['货到未入库','入库未到票','票到货未到','部分到货','分批开票','退货/不合格','赠品','跨月到货'];s=make(w,'05-入库异常','采购入库异常跟踪','每条异常必须连接PO、GR、发票、物料、Owner和月末处理。',['异常ID','异常类型','PO/合同','GR','发票','物料','数量','金额','发生日','Owner','月末处理','风险','状态','Closure'],exc.map((x,i)=>[`REC-${String(i+1).padStart(3,'0')}`,x,'','','','',0,0,null,'','','','未开始','']),{A:13,B:18,C:18,D:16,E:18,F:16,G:12,H:15,I:14,J:14,K:40,L:30,M:13,N:40},'ReceiptExceptions');s.getRange('C6:N13').format.fill=yellow;s.getRange('H6:H13').format.numberFormat='¥#,##0';s.getRange('I6:I13').format.numberFormat='yyyy-mm-dd';status(s.getRange('M6:M13'));
// movements
rows=Array.from({length:40},(_,i)=>[`MOV-${String(i+1).padStart(3,'0')}`,'','','','','',0,null,'','','','未复核','']);s=make(w,'06-异常收发','异常出入库与反过账日志','抓取无订单、负数量、夜间、月末集中、反过账和手工调整。',['交易ID','类型','物料','仓库','业务单号','操作人','数量','时间','反过账/删除','审批','异常说明','状态','复核'],rows,{A:13,B:18,C:16,D:18,E:18,F:14,G:12,H:18,I:20,J:18,K:40,L:14,M:32},'Movements');s.getRange('B6:M45').format.fill=yellow;
// BOM variance
rows=[['MO260801','FG-HC100','RM-IC-001',10000,1,10000,13000,3000,.30,'超耗','待工艺说明',''],['MO260802','FG-HC200','RM-PCB-002',3000,1,3000,3120,120,.04,'正常损耗','',''],...Array.from({length:38},(_,i)=>[`MO-${String(i+3).padStart(3,'0')}`,'','',0,0,0,0,0,0,'','',''])];s=make(w,'07-BOM超耗','生产工单与BOM用量差异','实际领料与标准用量差异按工单、物料、班组和原因追查。',['工单','产品','物料','完工数量','单位标准','标准用量','实际领料','差异数量','差异率','结论','原因/动作','复核'],rows,{A:15,B:16,C:16,D:14,E:14,F:14,G:14,H:14,I:12,J:16,K:44,L:28},'BOMVariance');s.getRange('D6:H45').format.numberFormat='#,##0.00';s.getRange('I6:I45').format.numberFormat='0.0%';s.getRange('J6:L45').format.fill=yellow;s.getRange('I6:I45').conditionalFormats.add('cellIs',{operator:'greaterThan',formula:.1,format:{fill:red,font:{color:'#C00000',bold:true}}});
// WIP
rows=[['MO260801','FG-HC100','组装',8000,10000,9500,100,2400,2360000,12,'正常',''],['MO260802','FG-HC200','测试',3500,3000,2800,50,650,1280000,25,'关注',''],...Array.from({length:38},(_,i)=>[`MO-${String(i+3).padStart(3,'0')}`,'','',0,0,0,0,0,0,0,'',''])];s=make(w,'08-在产品','在产品数量桥与工序滞留','期初WIP+投入-完工-报废=期末WIP；现场、工单和金额都要一致。',['工单','产品','工序','期初WIP','本期投入','本期完工','报废','期末WIP','WIP成本','滞留天数','状态','调查/动作'],rows,{A:15,B:16,C:16,D:14,E:14,F:14,G:12,H:14,I:16,J:13,K:14,L:44},'WIP');s.getRange('D6:I45').format.numberFormat='#,##0.00';s.getRange('K6:L45').format.fill=yellow;
// completion difference
rows=[['MO260801','FG-HC100',1000,1000,950,50,'线边/不良/漏入库待查','生产一部',new Date('2026-09-03'),'Open',''],...Array.from({length:39},(_,i)=>[`MO-${String(i+2).padStart(3,'0')}`,'',0,0,0,0,'','',null,'',''])];s=make(w,'09-完工差异','生产报工与完工入库差异','报工、质检合格、仓库入库和工单结算必须形成数量桥。',['工单','产品','报工数量','质检合格','仓库入库','差异','原因','Owner','截止日','状态','Closure'],rows,{A:15,B:16,C:14,D:14,E:14,F:12,G:42,H:14,I:14,J:13,K:38},'Completion');s.getRange('C6:F45').format.numberFormat='#,##0';s.getRange('G6:K45').format.fill=yellow;s.getRange('I6:I45').format.numberFormat='yyyy-mm-dd';status(s.getRange('J6:J45'),['Open','In Progress','Resolved','Closed']);
// count plan, blind, differences
rows=[['2026年年末全面盘点','东莞工厂全部仓库',new Date('2026-12-31'),'18:00-24:00','冻结；紧急移动单独编号','仓储经理','财务监盘/内审观察','盲盘+跨组复盘','未开始',''],['2026Q3循环盘点','高价值芯片/负库存SKU',new Date('2026-09-30'),'20:00-22:00','冻结目标库位','仓库主管','成本会计','盲盘','未开始','']];s=make(w,'10-盘点计划','存货盘点计划','明确范围、截点、移动控制、分组、盲盘、复盘、抽盘和报告。',['盘点','范围','基准日','时间','移动控制','负责人','独立监督','方法','状态','备注'],rows,{A:26,B:34,C:14,D:18,E:36,F:16,G:26,H:20,I:14,J:42},'CountPlan');s.getRange('C6:C7').format.numberFormat='yyyy-mm-dd';s.getRange('I6:J7').format.fill=yellow;status(s.getRange('I6:I7'));
rows=d.inventory.map((x,i)=>[`CNT-${String(i+1).padStart(3,'0')}`,x[0],x[1],x[4],x[3],'','','','','未盘','']);s=make(w,'11-盲盘表','存货盲盘表','不显示账面数量。盘点人填写实盘数量、批次、状态和签字。',['盘点ID','物料','名称','仓库/库位','单位','批次/序列','实盘数量','质量状态','盘点人','状态','备注'],rows,{A:13,B:16,C:26,D:26,E:10,F:22,G:14,H:16,I:14,J:13,K:42},'BlindCount');s.getRange('F6:K23').format.fill=yellow;status(s.getRange('J6:J23'),['未盘','已初盘','已复盘','已确认']);
rows=[['DIF-001','RM-IC-001','原料库-A01',18000,17800,-200,86,-17200,'盘亏待查','仓库主管',new Date('2026-09-05'),'冻结该库位','Open',''],['DIF-002','RM-ERR-009','线边库-L01',-300,0,300,86,25800,'负库存更正','生产主管',new Date('2026-09-03'),'禁止超发','Open',''],...Array.from({length:38},(_,i)=>[`DIF-${String(i+3).padStart(3,'0')}`,'','',0,0,0,0,0,'','',null,'','',''])];s=make(w,'12-盘点差异','盘点差异调查与Closure','不能只写“查明原因”。保留重盘、单据、日志、责任和调账证据。',['差异ID','物料','仓库','账面数','实盘数','差异数','单位成本','差异金额','原因','Owner','截止日','临时控制','状态','Closure证据'],rows,{A:13,B:16,C:22,D:13,E:13,F:13,G:14,H:16,I:32,J:14,K:14,L:28,M:14,N:40},'CountDiff');s.getRange('D6:H45').format.numberFormat='#,##0.00';s.getRange('I6:N45').format.fill=yellow;s.getRange('K6:K45').format.numberFormat='yyyy-mm-dd';status(s.getRange('M6:M45'),['Open','In Progress','Resolved','Closed','Accepted Risk']);
// aging and obsolete
s=make(w,'13-库龄','库存库龄分析','库龄是风险信号，不是统一跌价比例。',['物料','名称','类别','仓库','数量','金额','最后移动日','库龄天数','0-30','31-90','91-180','181-365','>365','业务说明'],d.inventory.map(x=>[x[0],x[1],x[2],x[4],x[5],x[7],new Date(x[8]),x[9],x[9]<=30?x[7]:0,x[9]>30&&x[9]<=90?x[7]:0,x[9]>90&&x[9]<=180?x[7]:0,x[9]>180&&x[9]<=365?x[7]:0,x[9]>365?x[7]:0,'']),{A:16,B:26,C:17,D:25,E:13,F:15,G:15,H:12,I:14,J:14,K:14,L:14,M:14,N:42},'Aging');s.getRange('E6:F23').format.numberFormat='#,##0.00';s.getRange('G6:G23').format.numberFormat='yyyy-mm-dd';s.getRange('I6:M23').format.numberFormat='¥#,##0';s.getRange('N6:N23').format.fill=yellow;
rows=d.inventory.filter(x=>x[9]>180||x[10].includes('呆滞')).map((x,i)=>[`OBS-${String(i+1).padStart(3,'0')}`,x[0],x[1],x[5],x[7],new Date(x[8]),x[9],x[10],'','','',0,null,'Open','']);s=make(w,'14-呆滞库存','呆滞库存责任与处置','逐项记录形成原因、责任、使用/销售/退供/替代/报废方案和预计损失。',['ID','物料','名称','数量','金额','最后移动日','库龄','状态','形成原因','责任部门','处理方案','预计损失','预计完成日','状态','Closure'],rows,{A:13,B:16,C:26,D:13,E:16,F:15,G:12,H:16,I:34,J:16,K:42,L:16,M:15,N:14,O:40},'Obsolete');s.getRange('D6:E15').format.numberFormat='#,##0.00';s.getRange('F6:F15').format.numberFormat='yyyy-mm-dd';s.getRange('I6:O15').format.fill=yellow;s.getRange('L6:L15').format.numberFormat='¥#,##0';s.getRange('M6:M15').format.numberFormat='yyyy-mm-dd';status(s.getRange('N6:N15'),['Open','有计划','执行中','Closed']);
// offsite/transfer
rows=[['OFF-001','OUT-1001','宏达电子','供应商外协仓',5000,650000,new Date('2026-08-31'),'对账+视频抽码','采购部','正常',''],['OFF-002','3PL-1001','苏州物流','第三方仓',1500,1020000,new Date('2026-08-31'),'对账+循环盘点','物流部','正常',''],['OFF-003','GIT-1001','客户A','客户/物流在途',1800,1224000,new Date('2026-08-31'),'签收+期后销售','销售部','待签收','']];s=make(w,'15-外仓与调拨','外仓、委外、寄售和调拨跟踪','实物不在本地时组合使用对账、函证、视频、期后交易和现场检查。',['ID','物料','保管方','地点/类型','数量','金额','对账日','验证方式','Owner','状态','差异/动作'],rows,{A:13,B:16,C:24,D:24,E:14,F:16,G:14,H:30,I:14,J:14,K:44},'Offsite');s.getRange('E6:F8').format.numberFormat='#,##0.00';s.getRange('G6:G8').format.numberFormat='yyyy-mm-dd';s.getRange('H6:K8').format.fill=yellow;
// impairment
rows=d.inventory.map((x,i)=>[`NRV-${String(i+1).padStart(3,'0')}`,x[0],x[1],x[2],x[5],x[6],0,0,0,0,0,0,'','','']);s=make(w,'16-跌价测算','存货跌价与可变现净值测算','业务提供售价/用途事实，财务按成本与NRV孰低独立测算。',['测试ID','物料','名称','类别','数量','单位成本','估计售价','至完工成本','销售费用','单位NRV','应计提单价','应计提金额','证据','结论','复核'],rows,{A:13,B:16,C:25,D:16,E:13,F:14,G:14,H:15,I:14,J:14,K:15,L:16,M:42,N:18,O:30},'NRV');s.getRange('E6:L23').format.numberFormat='#,##0.00';s.getRange('G6:O23').format.fill=yellow;
// scrap/waste
rows=Array.from({length:30},(_,i)=>[`SCR-${String(i+1).padStart(3,'0')}`,'','','',0,0,'','','','','','','','','Open','']);s=make(w,'17-报废申请','存货报废申请与见证','业务申请、技术鉴定、实物隔离、审批、见证、系统出库和税务资料闭环。',['申请ID','物料','批次','原因','数量','成本','鉴定','审批','实物位置','处置方式','见证人','系统出库','税务资料','责任','状态','Closure'],rows,{A:13,B:16,C:16,D:30,E:13,F:16,G:34,H:22,I:24,J:18,K:16,L:18,M:34,N:20,O:14,P:38},'Scrap');s.getRange('B6:P35').format.fill=yellow;s.getRange('E6:F35').format.numberFormat='#,##0.00';status(s.getRange('O6:O35'),['Open','鉴定中','待审批','执行中','Closed']);
rows=Array.from({length:30},(_,i)=>[`WST-${String(i+1).padStart(3,'0')}`,'',0,0,0,'','','','','','','','','']);s=make(w,'18-废料处置','废料、边角料和残次品处置','称重、定价、出门、开票、公司收款和系统数量必须一致。',['处置ID','废料类型','期初数量','本期增加','出售/处置数量','称重单','买方','单价','价款','审批','出门单','发票','收款','差异'],rows,{A:13,B:20,C:13,D:13,E:16,F:20,G:22,H:13,I:15,J:18,K:18,L:18,M:18,N:36},'Waste');s.getRange('B6:N35').format.fill=yellow;s.getRange('C6:E35').format.numberFormat='#,##0.00';s.getRange('H6:I35').format.numberFormat='¥#,##0.00';
// close checklist
let ck=['锁定所有仓库月末收发截点并保存单据编号区间','检查月末前后5日大额入库、出库、退货和调拨截止','检查货到未入库、入库未到票、票到货未到','完成未到票暂估并防止与正式发票重复','逐笔分析所有负库存SKU并评估成本影响','总账存货科目与存货/成本模块核对','存货模块数量与WMS/仓库台账核对','复核手工库存调整、反过账和成本修改日志','检查工单领退料、补料、替代料和BOM超耗','建立WIP数量桥并与现场/工单一致','核对报工、质检、完工入库和工单结算','核对出库、签收、收入、发票和营业成本','检查发出商品、寄售和客户退货','清理同法人未达调拨并识别跨法人交易','取得委外、3PL和客户仓对账证据','导出>180天和>365天库存并取得计划','更新呆滞Owner、损失、期限和状态','完成停产、质量、售价下降的NRV测算','检查报废、不良和废料处置闭环','盘点差异批准、入账、追责和整改','输出库存一页管理报告'];s=make(w,'19-月末Checklist','存货月末检查清单','每项填写责任人、期限、证据、异常、处理、复核和关闭。',['明确动作','责任人','期限','证据路径','异常金额','处理','状态','复核人','关闭日'],ck.map(x=>[x,'','D+3','',0,'','未开始','',null]),{A:62,B:15,C:11,D:38,E:15,F:40,G:13,H:14,I:14},'CloseChecklist');s.getRange('B6:I26').format.fill=yellow;s.getRange('E6:E26').format.numberFormat='¥#,##0';s.getRange('I6:I26').format.numberFormat='yyyy-mm-dd';status(s.getRange('G6:G26'));
// takeover
rows=[['第一周','总账、模块、WMS和权限','完成对账；导出负库存、前十大、库龄和外仓','','未开始'],['第一周','最近盘点和差异','定位未关闭及批量调整','','未开始'],['第一周','见仓库/计划/生产/采购/销售/IT','确认责任和数据来源','','未开始'],['第一个月','抽盘与主数据','卡到物、物到账；检查一物多码和单位','','未开始'],['第一个月','WIP/BOM/完工','重做数量桥和超耗分析','','未开始'],['第一个月','呆滞/NRV/废料','逐项核实并列Issue','','未开始'],['前三个月','制度、盘点、月结、权限','建立运行机制和Closure','','未开始'],['前三个月','管理报告和S&OP','把库存与现金、预测和决策连接','','未开始']];s=make(w,'20-接手检查','新财务主管接手存货检查','记录已取得资料、发现、临时控制、历史责任边界和关闭。',['阶段','事项','明确动作','发现/证据','状态'],rows,{A:14,B:30,C:58,D:50,E:13},'Takeover');s.getRange('D6:E13').format.fill=yellow;status(s.getRange('E6:E13'));
// KPIs, one-page, risks, issues, cases, sources
s=make(w,'21-核心指标','存货管理核心指标','指标异常后按类别、SKU、工厂、仓库、产品、订单、责任人和月份下钻。',['指标','公式/定义','管理意义','异常后查什么','主管动作','频率'],d.metrics,{A:24,B:34,C:38,D:48,E:44,F:12},'Metrics');
rows=[['总库存','2,327万元','与上月/预算/收入比较','解释量、价、结构和现金'],['周转天数','约111天','分原料/WIP/成品','结合缺货率判断'],['长期与呆滞','>365天、停产库存','列前五SKU和预计损失','Owner+方案+期限'],['盘点与数据','负库存、差异、手工调整','说明报表和舞弊风险','临时控制+系统整改'],['本月决策','退供/促销/替代/报废/权限','预计释放现金和避免损失','请管理层批准具体事项']];s=make(w,'22-一页管理报告','存货一页管理层报告','管理结论应说明金额、根因、现金影响、行动、Owner、期限和需要的决策。',['区域','本月结果','关键分析','行动/决策请求'],rows,{A:25,B:28,C:56,D:56},'ManagementReport');s.getRange('B6:D10').format.fill=yellow;
let risks=[['虚假入库','期末集中GR、无质检/门禁','期后冲回、供应商、现场'],['少结转成本','收入增长但出库/成本不增','订单-出库-收入-成本'],['隐藏盘亏','盘点前批量调整、整齐尾数','调整前快照、盲盘和日志'],['账外库存','实物无编码或来源不明','物到账、合同和资金'],['私售废料','出门无处置、款入个人','称重、买方、银行、发票'],['采购仓库串通','超收、赠品消失、唯一供应商','PO-GR、价格、盘点、关联方'],['操纵跌价','比例突变、无SKU证据','逐项NRV和历史回测'],['越权删单改成本','同人创建删除、月末集中','权限日志、反过账和毛利']];s=make(w,'23-风险红旗','存货舞弊和控制红旗','先保全证据、控制实物和系统权限，再调查和升级。',['风险','典型红旗','检查动作'],risks,{A:26,B:50,C:64},'Risks');
rows=[['ISS-001','负库存RM-ERR-009','2026-08月结','成本会计','高','仓库禁止超发','2026-09-03','调查中','财务主管','Open',''],...Array.from({length:39},(_,i)=>[`ISS-${String(i+2).padStart(3,'0')}`,'','','','中','',null,'','','Open',''])];s=make(w,'24-Issue Log','存货问题跟踪与Closure','重大问题必须记录事实、Owner、截止、临时控制、升级、状态和关闭证据。',['Issue ID','问题','发现时间/方式','Owner','严重度','临时控制','截止日','处理方案','复核人','状态','Closure证据'],rows,{A:13,B:40,C:22,D:16,E:12,F:38,G:14,H:44,I:14,J:14,K:42},'IssueLog');s.getRange('B6:K45').format.fill=yellow;s.getRange('G6:G45').format.numberFormat='yyyy-mm-dd';s.getRange('E6:E45').dataValidation={rule:{type:'list',values:['低','中','高','重大']}};status(s.getRange('J6:J45'),['Open','In Progress','Resolved','Closed','Accepted Risk']);
s=make(w,'25-案例库','存货高频实战案例','填写“我的回答”用于面试和入职演练。',['编号','场景','第一步','沟通对象','调查/处理','升级条件','我的回答'],d.cases.map(x=>[...x,'']),{A:13,B:42,C:54,D:28,E:60,F:44,G:56},'Cases');s.getRange(`G6:G${5+d.cases.length}`).format.fill=yellow;
s=make(w,'26-资料来源','存货准则、内控和税务依据','实际税务处理按事项发生日、原因和地区再次核对最新有效口径。',['名称','文件号/机构','关系','官方链接'],d.sources,{A:52,B:42,C:62,D:66},'Sources');
w.recalculate();
const dash=await w.inspect({kind:'table',range:'00-管理看板!A5:D18',include:'values,formulas',tableMaxRows:20,tableMaxCols:8});await fs.writeFile(path.join(qa,'dashboard.ndjson'),dash.ndjson??String(dash));
const errors=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'final formula error scan'});await fs.writeFile(path.join(qa,'errors.ndjson'),errors.ndjson??String(errors));
for(const n of w.worksheets.items.map(x=>x.name)){const p=await w.render({sheetName:n,autoCrop:'all',scale:.45,format:'png'});await fs.writeFile(path.join(qa,`${n}.png`),new Uint8Array(await p.arrayBuffer()))}
const f=await SpreadsheetFile.exportXlsx(w);await f.save(path.join(out,'企业存货管理工具包.xlsx'));console.log(JSON.stringify({sheets:w.worksheets.items.length}));


