import fs from 'node:fs/promises';import path from'node:path';import{FileBlob,SpreadsheetFile}from'@oai/artifact-tool';
const base=path.dirname(new URL(import.meta.url).pathname.slice(1)),src=path.join('C:','Users','HZJ','Desktop','Git','work','ap_supplier_management_20260911','deliverables','应付账款及供应商管理工具包.xlsx'),out=path.join(base,'deliverables'),qa=path.join(base,'qa','xlsx');await fs.mkdir(out,{recursive:true});await fs.mkdir(qa,{recursive:true});
const w=await SpreadsheetFile.importXlsx(await FileBlob.load(src));const nav='#1F4E78',yellow='#FFF2CC',green='#E2F0D9',red='#FCE4D6',line='#B8C4CE',font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}function title(s,t,sub,n){s.showGridLines=false;s.getRange(`A1:${col(n)}1`).merge();s.getRange('A1').values=[[t]];s.getRange('A1').format={font:{name:font,size:16,bold:true},rowHeight:30};s.getRange(`A2:${col(n)}2`).merge();s.getRange('A2').values=[[sub]];s.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},wrapText:true,rowHeight:30}}function head(s,a){s.getRange(a).format={fill:nav,font:{name:font,size:8,bold:true,color:'#FFFFFF'},wrapText:true,horizontalAlignment:'center',verticalAlignment:'center',rowHeight:34,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}function body(s,a){s.getRange(a).format={font:{name:font,size:8},wrapText:true,verticalAlignment:'center',borders:{preset:'all',style:'thin',color:line}}}function widths(s,m){for(const[k,v]of Object.entries(m))s.getRange(`${k}:${k}`).format.columnWidth=v}function make(n,t,sub,h,rows,wm,tn){let s=w.worksheets.add(n);title(s,t,sub,h.length);s.getRange(`A5:${col(h.length)}5`).values=[h];head(s,`A5:${col(h.length)}5`);if(rows.length){s.getRange(`A6:${col(h.length)}${5+rows.length}`).values=rows;body(s,`A6:${col(h.length)}${5+rows.length}`);s.tables.add(`A5:${col(h.length)}${5+rows.length}`,true,tn).style='TableStyleMedium2'}widths(s,wm);s.freezePanes.freezeRows(5);s.freezePanes.freezeColumns(Math.min(3,h.length));return s}function status(r,vals=['未开始','进行中','待复核','已完成']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{bold:true,color:'#548235'}}});r.conditionalFormats.add('containsText',{text:'高',format:{fill:red,font:{bold:true,color:'#C00000'}}})}
let rows=Array.from({length:35},(_,i)=>[`VEN-${String(i+1).padStart(3,'0')}`,'','','','','','','','','','','','','待审批']);
let s=make('19-供应商准入','供应商准入与新增审批','采购提供商业资料，主数据岗录入；账户、税务、关联方和质量资质分别独立复核。',['申请号','供应商名称','统一社会信用代码','采购类别','营业执照/资质','纳税人及开票','银行户名/账号','关联方声明','比价/单一来源','质量评估','责任采购','风险等级','审批意见','状态'],rows,{A:13,B:26,C:22,D:18,E:22,F:20,G:30,H:20,I:28,J:24,K:16,L:13,M:35,N:13},'VendorOnboarding');s.getRange('B6:N40').format.fill=yellow;status(s.getRange('N6:N40'),['待审批','补资料','批准','拒绝','停用']);
rows=Array.from({length:30},(_,i)=>[`EXIT-${String(i+1).padStart(3,'0')}`,'','','','','','','','','','','未开始']);
s=make('20-供应商退出','供应商退出与未结事项','停用主数据前关闭未执行PO、在途、退货、质保、争议、预付和应付。',['退出号','供应商','退出原因','未执行PO','在途/退货','应付余额','预付余额','争议/质保','最后付款','主数据冻结','Closure证据','状态'],rows,{A:13,B:24,C:32,D:18,E:24,F:15,G:15,H:28,I:15,J:18,K:40,L:13},'VendorExit');s.getRange('B6:L35').format.fill=yellow;s.getRange('F6:G35').format.numberFormat='¥#,##0';status(s.getRange('L6:L35'));
rows=[['AP-DUAL-001','甲供应商',new Date('2026-01-01'),new Date('2026-03-31'),1000000,'=MAX(0,DATE(2026,3,1)-C6)','=MAX(0,DATE(2026,3,1)-D6)','=IF(G6=0,"未逾期",IF(G6<=30,"1-30",IF(G6<=60,"31-60",IF(G6<=90,"61-90",">90"))))','账龄60天但未逾期'],['AP-DUAL-002','乙供应商',new Date('2025-11-01'),new Date('2025-12-31'),600000,'=MAX(0,DATE(2026,3,1)-C7)','=MAX(0,DATE(2026,3,1)-D7)','=IF(G7=0,"未逾期",IF(G7<=30,"1-30",IF(G7<=60,"31-60",IF(G7<=90,"61-90",">90"))))','已逾期60天'],['AP-DUAL-003','丙供应商',new Date('2025-06-01'),new Date('2025-07-31'),300000,'=MAX(0,DATE(2026,3,1)-C8)','=MAX(0,DATE(2026,3,1)-D8)','=IF(G8=0,"未逾期",IF(G8<=30,"1-30",IF(G8<=60,"31-60",IF(G8<=90,"61-90",">90"))))','长期逾期']];
s=make('21-双账龄分析','应付账龄与逾期账龄','应付账龄回答负债存在多久；逾期账龄回答超过合同日多久。基准日2026-03-01。',['应付ID','供应商','确认日','到期日','余额','应付账龄天数','逾期天数','逾期段','说明'],rows,{A:15,B:24,C:14,D:14,E:16,F:16,G:14,H:14,I:35},'DualAging');s.getRange('C6:D8').format.numberFormat='yyyy-mm-dd';s.getRange('E6:E8').format.numberFormat='¥#,##0';
rows=[['REC-DIFF-001','示例供应商',1200000,1000000,'=C6-D6','','','','','','','','待核实'],...Array.from({length:29},(_,i)=>[`REC-DIFF-${String(i+2).padStart(3,'0')}`,'',0,0,'=C'+(i+7)+'-D'+(i+7),'','','','','','','','未开始'])];
s=make('22-对账差异底稿','供应商对账差异桥接','先统一主体、币种和截止日，再桥接未达发票、未达入库、暂估、退货、预付、付款和串户。',['对账ID','供应商','公司账余额','供应商账余额','差异','未达发票','未达收货/暂估','退货/红票','折扣/返利/扣款','预付/未达付款','重复/串户','Owner','状态'],rows,{A:15,B:24,C:16,D:16,E:14,F:18,G:22,H:18,I:22,J:20,K:18,L:16,M:13},'ReconciliationBridge');s.getRange('C6:M35').format.fill=yellow;s.getRange('C6:K35').format.numberFormat='¥#,##0';status(s.getRange('M6:M35'),['未开始','待核实','处理中','已关闭']);
const checks=['合同主体、有效期和审批完整','预算、请购和PO真实授权','货物/服务已验收且付款条件满足','发票或合法凭证真实合规且未重复','三单匹配通过或差异已批准','质量争议、退货、索赔和返利已考虑','已有预付、贷项和退款已核销','到期日正确；提前付有收益或批准','重复发票、申请、PO和付款检查完成','收款账户与主数据一致；变更已独立回拨','付款权限、制单、复核、网银授权分离','批次总额与现金计划和优先级一致'];rows=checks.map((x,i)=>[i+1,x,'是/否','','','','']);
s=make('23-付款前检查','付款审批逐项检查','“资料完整”必须拆成可验证的判断；任何高风险否项均不得形式签字。',['序号','检查事项','结论','异常说明','证据路径','复核人','复核日'],rows,{A:10,B:72,C:13,D:40,E:42,F:16,G:14},'PaymentPrecheck');s.getRange('C6:G17').format.fill=yellow;s.getRange('C6:C17').dataValidation={rule:{type:'list',values:['是','否','不适用']}};s.getRange('G6:G17').format.numberFormat='yyyy-mm-dd';
rows=[['DUP-001','S001','芯联电子','9144SIM001','INV-001','PO-001','REQ-001',226000,new Date('2026-08-10'),'=C6&D6&E6&H6','=D6&E6&H6','=IF(COUNTIF($J$6:$J$10,J6)>1,"疑似重复","正常")'],['DUP-002','S001','芯联电子','9144SIM001','INV-001','PO-001','REQ-002',226000,new Date('2026-08-11'),'=C7&D7&E7&H7','=D7&E7&H7','=IF(COUNTIF($J$6:$J$10,J7)>1,"疑似重复","正常")'],['DUP-003','S002','东莞精工','9144SIM002','INV-009','PO-009','REQ-009',113000,new Date('2026-08-12'),'=C8&D8&E8&H8','=D8&E8&H8','=IF(COUNTIF($J$6:$J$10,J8)>1,"疑似重复","正常")'],['DUP-004','S099','精工金属别名','9144SIM002','INV-010','PO-010','REQ-010',50000,new Date('2026-08-13'),'=C9&D9&E9&H9','=D9&E9&H9','=IF(COUNTIF($J$6:$J$10,J9)>1,"疑似重复","正常")'],['DUP-005','S003','华南塑胶','9144SIM003','INV-015','PO-015','REQ-015',90400,new Date('2026-08-14'),'=C10&D10&E10&H10','=D10&E10&H10','=IF(COUNTIF($J$6:$J$10,J10)>1,"疑似重复","正常")']];
s=make('24-重复付款扫描','重复发票与付款扫描','演示按供应商、税号、发票、PO、申请和金额组合查重；还需结合预付、贷项和银行批次。',['检查ID','供应商编码','供应商名称','税号','发票号','PO','付款申请','金额','付款日','完整键','跨编码键','结果'],rows,{A:13,B:13,C:24,D:20,E:16,F:14,G:16,H:15,I:14,J:35,K:35,L:15},'DuplicateScan');s.getRange('H6:H10').format.numberFormat='¥#,##0';s.getRange('I6:I10').format.numberFormat='yyyy-mm-dd';s.getRange('L6:L10').conditionalFormats.add('containsText',{text:'疑似重复',format:{fill:red,font:{bold:true,color:'#C00000'}}});
rows=[['PRI-001','芯联电子','核心料停线风险',new Date('2026-09-01'),2260000,5,5,5,2,3,'=F6*30+G6*25+H6*15+I6*10+J6*20','待决策'],['PRI-002','普通办公供应商','普通办公耗材',new Date('2026-09-05'),100000,1,3,1,1,2,'=F7*30+G7*25+H7*15+I7*10+J7*20','待决策'],['PRI-003','东莞精工','逾期且无争议',new Date('2026-08-04'),856000,4,5,4,1,4,'=F8*30+G8*25+H8*15+I8*10+J8*20','待决策'],...Array.from({length:27},(_,i)=>[`PRI-${String(i+4).padStart(3,'0')}`,'','',null,0,0,0,0,0,0,`=F${i+9}*30+G${i+9}*25+H${i+9}*15+I${i+9}*10+J${i+9}*20`,'未开始'])];
s=make('25-付款优先级','现金紧张付款排序','评分只是决策支持；工资、税款、到期银行债务等先单列，重大取舍由授权管理层决定。',['计划ID','供应商','事项','到期日','金额','连续性1-5','合同/违约1-5','替代性1-5','经济收益1-5','声誉/规模1-5','加权分','状态'],rows,{A:13,B:23,C:30,D:14,E:16,F:14,G:16,H:14,I:15,J:16,K:14,L:13},'PaymentPriority');s.getRange('D6:D35').format.numberFormat='yyyy-mm-dd';s.getRange('E6:E35').format.numberFormat='¥#,##0';s.getRange('F6:J35').format.fill=yellow;status(s.getRange('L6:L35'),['未开始','待决策','已批准','已付款','延期']);
rows=Array.from({length:40},(_,i)=>[`ANOM-${String(i+1).padStart(3,'0')}`,'','','',0,'','','','','','','Open']);
s=make('26-异常余额','应付与预付异常余额','先查真实业务和未清项，再决定调账、重分类、追回或保留。',['编号','供应商','科目','异常类型','金额','可能原因','核实资料','会计处理','管理动作','Owner','截止日','状态'],rows,{A:13,B:24,C:18,D:24,E:15,F:38,G:42,H:38,I:38,J:16,K:14,L:13},'BalanceAnomalies');s.getRange('B6:L45').format.fill=yellow;s.getRange('E6:E45').format.numberFormat='¥#,##0';s.getRange('K6:K45').format.numberFormat='yyyy-mm-dd';status(s.getRange('L6:L45'),['Open','处理中','待复核','Closed']);
rows=[['同账户多供应商','供应商主数据','银行账号分组计数','无关联主体共享账户','主数据/采购/法务','未开始'],['供应商与员工账户重合','供应商+HR主数据','银行账号匹配','资金流向员工/亲属','财务主管/HR','未开始'],['重复发票与付款','AP/发票/银行','发票号、税号、金额、日期组合','重复票、重复申请或退款未收','AP主管','未开始'],['贴审批阈值','付款申请','按合同/供应商/日期合并','拆单规避权限','财务主管','未开始'],['新供应商大额预付','供应商+预付','新增30天内预付比例','虚假供应商或关联方占款','采购总监/财务经理','未开始'],['账户变更后立即付款','变更日志+银行','变更7天内付款','邮箱入侵/篡改','资金主管','未开始'],['周末深夜操作','ERP日志','非工作时间手工单据','规避监督','IT/财务主管','未开始'],['收货后快速退货','GR/退货/付款','30天内退货率','虚假验收/截止操纵','仓库/质量','未开始'],['长期整数暂估','GRNI','整数金额及90天账龄','无可靠估计/平滑成本','总账/AP','未开始'],['休眠供应商恢复','主数据+采购','12个月无交易后恢复','绕过准入','采购/主数据','未开始']];
s=make('27-舞弊数据测试','采购与付款舞弊数据测试','每项测试要保留提取口径、运行日期、异常数量、核实人和关闭证据。',['测试','数据源','规则','红旗','Owner','状态'],rows,{A:30,B:28,C:55,D:45,E:22,F:13},'FraudTests');status(s.getRange('F6:F15'));
rows=[['第1周','供应商主数据和银行账户','导出供应商、账户变更、权限和关联方','资料签收+基准日快照','','未开始'],['第1周','AP/GL、GRNI、预付和Top供应商','重做对账并扫描长期和负数余额','历史Issue清单','','未开始'],['第1个月','月结与付款批次','独立重做一次截止、对账和大额付款复核','临时控制+管理层报告','','未开始'],['第1个月','账户变更和重复付款','抽查6个月日志和运行查重','异常退款/整改','','未开始'],['第2个月','分级、账期、对账和三单例外','评估政策与实际执行','流程缺口清单','','未开始'],['第3个月','制度、KPI、周会和系统优化','关闭高风险并形成路线图','90日复盘','','未开始']];
s=make('28-前三月接手','新财务主管30/60/90日计划','发现历史问题后记录发现日、基准数据、临时控制、Owner和需管理层决定事项。',['阶段','领域','动作','输出','发现/证据','状态'],rows,{A:16,B:34,C:62,D:38,E:45,F:13},'Takeover90');s.getRange('E6:F11').format.fill=yellow;status(s.getRange('F6:F11'));
// Expand the original monthly checklist with the missing explicit checks.
const ck=w.worksheets.getItem('12-月末Checklist');const extra=[['扫描同税号、同银行账号、同地址电话的重复供应商','主数据管理员','D+3','主数据重复报告','保留主记录和历史映射','未开始','',null],['复核本月全部供应商银行账户变更及变更后付款','资金主管','D+4','回拨、审批、网银清单','全部独立验证','未开始','',null],['形成应付、预付、其他往来供应商360度余额','总账/AP','D+3','多科目余额表','每个异常有实质解释','未开始','',null],['检查预付已逾交付日、大额预付和关联方预付','采购/财务主管','D+4','合同里程碑、催交/退款','有履约、退款或升级方案','未开始','',null],['核对关联方供应商完整性、价格和审批','财务主管','D+4','关联方清单、比价、合同','披露和审批完整','未开始','',null],['运行重复发票、重复申请、重复付款和红票未冲测试','AP主管','D+4','查重日志','异常全部关闭或冻结','未开始','',null]];ck.getRange('A15:H20').values=extra;body(ck,'A15:H20');ck.getRange('F15:H20').format.fill=yellow;status(ck.getRange('F15:F20'));ck.getRange('H15:H20').format.numberFormat='yyyy-mm-dd';
// Add only the seven case gaps to the existing case library.
const cs=w.worksheets.getItem('17-案例库');const newCases=[['AP-019','供应商称公司少付30万元','锁定截止日和主体，形成双方余额桥','AP/采购/供应商','排查未达、暂估、退货、预付、付款、串户和重复票','重大或跨期差异',''],['AP-020','供应商注销但账上仍有余额','核验注销、清算和债权承接','法务/AP/采购','确认合法债权人和付款路径，不直接转收益','债权人不明或异常账户',''],['AP-021','同一供应商存在多个名称和编码','按税号、银行账户、地址电话穿透','主数据/AP/采购','冻结新增编码，查重后建立主从映射','与员工账户重合',''],['AP-022','供应商返利多年未确认','核对协议、采购量、达标和供应商确认','采购/成本/AP/税务','按适用政策分配至存货/成本并完成贷项核销','返利流入个人',''],['AP-023','老板要求无完整资料付款','列明缺失资料、业务事实和资金风险','老板/采购/法务','补验收、限额例外、担保或暂停并书面留痕','无真实业务或个人账户',''],['AP-024','120万元付款拆成三笔40万元','按同合同、供应商和商业目的合并判断','采购/财务经理','冻结拆分，恢复完整审批','反复拆单或关联方',''],['AP-025','关联方预付一年未交货','核实商业目的、定价、履约和资金占用','管理层/法务/税务','要求履约、担保或退款并评估减值迹象','资金循环或无商业目的','']];cs.getRange('A24:G30').values=newCases;body(cs,'A24:G30');cs.getRange('G24:G30').format.fill=yellow;
w.recalculate();const errors=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:500},summary:'AP integrated workbook error scan'});await fs.writeFile(path.join(qa,'errors.ndjson'),errors.ndjson??String(errors));const names=w.worksheets.items.map(x=>x.name);for(const n of names){const p=await w.render({sheetName:n,autoCrop:'all',scale:.52,format:'png'});await fs.writeFile(path.join(qa,`${n}.png`),new Uint8Array(await p.arrayBuffer()))}const f=await SpreadsheetFile.exportXlsx(w);await f.save(path.join(out,'应付账款及供应商管理工具包（复核修订版）.xlsx'));console.log(JSON.stringify({sheets:names.length,names}));
