import fs from 'node:fs/promises';
import path from 'node:path';
import {SpreadsheetFile,Workbook} from '@oai/artifact-tool';

const base=path.dirname(new URL(import.meta.url).pathname.slice(1));
const out=path.join(base,'deliverables'); const qa=path.join(base,'qa');
await fs.mkdir(out,{recursive:true}); await fs.mkdir(qa,{recursive:true});
const d=JSON.parse(await fs.readFile(path.join(base,'content.json'),'utf8'));
const nav='#17365D', blue='#D9EAF7', pale='#F4F7FA', yellow='#FFF2CC', green='#E2F0D9', red='#FCE4D6', line='#D9D9D9', font='Microsoft YaHei';
function col(n){let s='';while(n){n--;s=String.fromCharCode(65+n%26)+s;n=Math.floor(n/26)}return s}
function title(s,t,sub,n){s.showGridLines=false;s.getRange(`A1:${col(n)}1`).merge();s.getRange('A1').values=[[t]];s.getRange('A1').format={font:{name:font,size:16,bold:true,color:'#000000'},rowHeight:30};s.getRange(`A2:${col(n)}2`).merge();s.getRange('A2').values=[[sub]];s.getRange('A2').format={font:{name:font,size:9,italic:true,color:'#666666'},rowHeight:28,wrapText:true}}
function head(s,a){s.getRange(a).format={fill:nav,font:{name:font,size:8,bold:true,color:'#FFFFFF'},wrapText:true,horizontalAlignment:'center',verticalAlignment:'center',rowHeight:34,borders:{preset:'all',style:'thin',color:'#FFFFFF'}}}
function body(s,a){s.getRange(a).format={font:{name:font,size:8,color:'#000000'},wrapText:true,verticalAlignment:'center',borders:{preset:'all',style:'thin',color:line}}}
function widths(s,m){for(const[k,v]of Object.entries(m))s.getRange(`${k}:${k}`).format.columnWidth=v}
function sheet(w,n,t,sub,h,rows,wm,tn){let s=w.worksheets.add(n);title(s,t,sub,h.length);s.getRange(`A5:${col(h.length)}5`).values=[h];head(s,`A5:${col(h.length)}5`);if(rows.length){s.getRange(`A6:${col(h.length)}${5+rows.length}`).values=rows;body(s,`A6:${col(h.length)}${5+rows.length}`);s.tables.add(`A5:${col(h.length)}${5+rows.length}`,true,tn).style='TableStyleMedium2'}widths(s,wm);s.freezePanes.freezeRows(5);return s}
function status(r,vals=['未开始','进行中','待复核','已完成']){r.dataValidation={rule:{type:'list',values:vals}};r.conditionalFormats.add('containsText',{text:'已完成',format:{fill:green,font:{color:'#548235',bold:true}}});r.conditionalFormats.add('containsText',{text:'待复核',format:{fill:yellow}});r.conditionalFormats.add('containsText',{text:'未通过',format:{fill:red,font:{color:'#C00000',bold:true}}})}
async function exportBook(w,file,prefix,names){w.recalculate();const err=await w.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!|#SPILL!|#CALC!',options:{useRegex:true,maxResults:300},summary:'final formula error scan'});await fs.writeFile(path.join(qa,`${prefix}_errors.ndjson`),err.ndjson??String(err));for(const n of names){const p=await w.render({sheetName:n,autoCrop:'all',scale:.65,format:'png'});await fs.writeFile(path.join(qa,`${prefix}_${n}.png`),new Uint8Array(await p.arrayBuffer()))}const f=await SpreadsheetFile.exportXlsx(w);await f.save(path.join(out,file))}

// Opportunity map workbook
const w1=Workbook.create();let s=w1.worksheets.add('00-总览');title(s,'企业财务自动化机会地图','先测量，再评分，再做ROI。黄色单元格为可修改假设。',8);
s.getRange('A5:D5').values=[['指标','当前','判断标准','用途']];head(s,'A5:D5');s.getRange('A6:A11').values=[['项目数'],['优先项目'],['总原型投入小时'],['月度节约小时'],['平均回收期（月）'],['AI Agent项目']];s.getRange('B6:B11').formulas=[["=COUNTA('01-机会地图'!A6:A25)"],["=COUNTIF('01-机会地图'!Q6:Q25,\"优先\")"],["=SUM('01-机会地图'!L6:L25)"],["=SUM('01-机会地图'!M6:M25)"],["=AVERAGE('02-ROI测算'!N6:N25)"],["=COUNTIF('01-机会地图'!K6:K25,\"*Agent*\")"]];s.getRange('C6:C11').values=[[20],[5],['按项目'],['案例假设'],['越短越优先'],['安排在最后']];s.getRange('D6:D11').values=[['全部候选'],['银行、暂估、挂账、TB、报表'],['不等于生产上线工时'],['进入企业后重测'],['同时考虑风险与复用'],['先稳定数据、规则和权限']];body(s,'A6:D11');s.getRange('B10').format.numberFormat='0.0';widths(s,{A:24,B:18,C:26,D:46});
let rows=d.projects.map((p,i)=>[p.id,p.process,p.name,i<5?'高频':'月度',p.hours>35?5:3,p.saved,p.rules.length>35?4:5,i%4===0?3:4,p.level>=4?5:4,p.level>=4?4:2,p.tool,p.level,p.hours,p.saved,'人工判断、复核和批准',`=IF(AND(G${i+6}>=4,H${i+6}>=3,I${i+6}<=4),\"高\",\"中\")`,[0,4,7,8,15].includes(i)?'优先':'后续']);
s=sheet(w1,'01-机会地图','财务自动化机会地图','评分为初筛，必须结合权限门槛和ROI。',['编号','流程','任务','频率','每次耗时分钟','月度节约小时','规则清晰度1-5','数据结构1-5','判断程度1-5','风险1-5','推荐工具','难度Level','原型小时','预计月省小时','人工保留步骤','自动化潜力','优先级'],rows,{A:12,B:16,C:26,D:11,E:15,F:15,G:14,H:14,I:14,J:11,K:26,L:12,M:13,N:15,O:34,P:14,Q:11},'OpportunityMap');s.getRange('E6:J25').format.fill=yellow;s.getRange('L6:N25').format.fill=yellow;s.getRange('Q6:Q25').conditionalFormats.add('containsText',{text:'优先',format:{fill:green,font:{bold:true,color:'#548235'}}});
rows=d.projects.map((p,i)=>[p.id,p.name,12,p.saved,120,0,p.hours,180,0,2,`=D${i+6}*C${i+6}*E${i+6}+F${i+6}`,`=G${i+6}*H${i+6}+I${i+6}+J${i+6}*D${i+6}*E${i+6}`,`=IF(L${i+6}=0,0,(K${i+6}-L${i+6})/L${i+6})`,`=IF(D${i+6}*E${i+6}=0,999,L${i+6}/(D${i+6}*E${i+6}))`,`=IF(N${i+6}<=6,\"优先\",IF(N${i+6}<=12,\"评估\",\"暂缓\"))`]);
s=sheet(w1,'02-ROI测算','自动化项目ROI','黄色为假设；首年收益和TCO均以人民币及小时成本估算。',['编号','项目','收益月数','月省小时','小时人工成本','其他年收益','开发小时','开发小时成本','软件及培训','月维护小时','首年收益','首年TCO','首年ROI','回收期月','建议'],rows,{A:12,B:26,C:10,D:12,E:13,F:14,G:12,H:14,I:14,J:13,K:15,L:15,M:12,N:12,O:11},'ROIModel');s.getRange('C6:J25').format.fill=yellow;s.getRange('K6:L25').format.numberFormat='¥#,##0';s.getRange('M6:M25').format.numberFormat='0.0%';s.getRange('N6:N25').format.numberFormat='0.0';s.getRange('O6:O25').conditionalFormats.add('containsText',{text:'优先',format:{fill:green,font:{bold:true}}});
s=sheet(w1,'03-评分模型','自动化可行性评分','项目得分 = 收益 + 可行性 + 可维护性 - 风险扣分。',['维度','指标','权重','5分标准','1分标准'],[['收益','月度人工耗时',15,'每月超过20小时','每月不足1小时'],['收益','发生频率',8,'日频','年频'],['收益','错误风险降低',12,'可明显减少重大错漏','影响很小'],['收益','复用范围',8,'多主体多期间','单次使用'],['收益','月结关键程度',7,'关键路径','非关键'],['可行性','规则清晰度',12,'可完全写成规则','主要靠判断'],['可行性','数据结构化',10,'稳定表格/API','非结构化且不完整'],['可行性','来源稳定性',8,'字段长期稳定','经常变化'],['可行性','异常比例',5,'低于5%','超过50%'],['可行性','工具可用性',5,'ERP/API可用','无法合法取得'],['维护','维护难度',5,'财务可自行修改','依赖外部开发'],['维护','用户接受',3,'输入标准稳定','经常不按规则'],['维护','回退能力',2,'有验证过的手工流程','无回退']],{A:14,B:24,C:10,D:32,E:32},'ScoreModel');
s=sheet(w1,'04-工具矩阵','财务问题与工具选择','从最简单、最确定且易维护的方案开始。',['工具','适用问题','典型场景','不适合'],d.tools,{A:16,B:38,C:36,D:36},'ToolMatrix');
s=sheet(w1,'05-全景评估','各财务领域自动化评估','自动化结果为建议和异常清单，不等于业务正确。',['领域','典型任务','重复','规则','判断','价值','工具','人工保留'],d.panorama,{A:16,B:34,C:10,D:10,E:10,F:10,G:24,H:38},'Panorama');
s=sheet(w1,'06-3个月路线','三个月学习路线','Agent安排在数据、规则、工具和权限成熟之后。',['周','重点','练习成果','完成状态'],[[1,'测量、ROI与Excel','报表勾稽原型','未开始'],[2,'Power Query清洗','统一字段模板','未开始'],[3,'银行对账','对账工具','未开始'],[4,'长期挂账','异常清单','未开始'],[5,'Python与pandas','读写合并','未开始'],[6,'暂估匹配','到票差异','未开始'],[7,'TB规则库','异常余额','未开始'],[8,'UAT和并行验证','上线证据','未开始'],[9,'Power BI模型','月结看板','未开始'],[10,'API和RPA边界','接口决策','未开始'],[11,'AI辅助','合同摘要','未开始'],[12,'受控Agent','Close Agent概念验证','未开始']],{A:8,B:28,C:34,D:13},'Roadmap');status(s.getRange('D6:D17'));
await exportBook(w1,'企业财务自动化机会地图.xlsx','opportunity',['00-总览','01-机会地图','02-ROI测算','03-评分模型','04-工具矩阵','05-全景评估','06-3个月路线']);

// UAT workbook
const w2=Workbook.create();s=w2.worksheets.add('00-UAT看板');title(s,'财务自动化UAT与控制工具','测试不仅验证正常数据，还要验证空值、重复、边界、错误格式和失败回退。',6);s.getRange('A5:D5').values=[['指标','结果','要求','说明']];head(s,'A5:D5');s.getRange('A6:A10').values=[['项目数'],['测试案例数'],['未通过'],['待复核'],['已批准上线']];s.getRange('B6:B10').formulas=[["=COUNTA('01-项目清单'!A6:A25)"],["=COUNTA('02-UAT测试'!A6:A105)"],["=COUNTIF('02-UAT测试'!K6:K105,\"未通过\")"],["=COUNTIF('02-UAT测试'!K6:K105,\"待复核\")"],["=COUNTIF('01-项目清单'!L6:L25,\"已上线\")"]];s.getRange('C6:C10').values=[[20],['按项目补充'],[0],[0],['需批准']];s.getRange('D6:D10').values=[['项目负责人'],['正常/边界/异常/脏数据/回归'],['必须关闭或接受风险'],['指定复核人'],['不得由开发者单独批准']];body(s,'A6:D10');widths(s,{A:20,B:14,C:18,D:46});
rows=d.projects.map(p=>[p.id,p.name,p.process,'','',p.tool,p.level,'未开始','','','否','未上线']);s=sheet(w2,'01-项目清单','自动化项目清单','记录Owner、版本、UAT和上线责任。',['编号','项目','流程','Owner','版本','工具','Level','状态','UAT负责人','批准人','Fallback验证','上线状态'],rows,{A:12,B:26,C:18,D:14,E:10,F:26,G:9,H:12,I:16,J:14,K:16,L:13},'ProjectList');s.getRange('D6:L25').format.fill=yellow;status(s.getRange('H6:H25'));s.getRange('K6:K25').dataValidation={rule:{type:'list',values:['是','否']}};s.getRange('L6:L25').dataValidation={rule:{type:'list',values:['未上线','试运行','已上线','已停用']}};
let testRows=[];for(const p of d.projects.slice(0,5)){for(const [typ,input,exp] of [['正常','唯一键且字段完整','按规则通过或匹配'],['边界','金额等于阈值或日期在截止日','按书面规则稳定处理'],['异常','重复、方向异常或组合关系','进入异常清单'],['脏数据','空值、文本金额或错误日期','停止并明确报错'],['回归','修改规则后重跑历史集','旧功能没有被破坏']])testRows.push([`${p.id}-${typ}`,p.id,typ,input,exp,'','','','','','待复核','',''])}
while(testRows.length<100)testRows.push([`UAT-${String(testRows.length+1).padStart(3,'0')}`,'','','','','','','','','','未开始','','']);
s=sheet(w2,'02-UAT测试','UAT测试案例','必须填写实际结果和证据路径。',['案例号','项目号','类型','输入场景','预期结果','实际结果','输入文件','输出文件','执行人','执行日','结果','异常说明','复核人'],testRows,{A:16,B:12,C:11,D:34,E:34,F:34,G:28,H:28,I:14,J:14,K:12,L:34,M:14},'UATTests');s.getRange('F6:M105').format.fill=yellow;s.getRange('J6:J105').format.numberFormat='yyyy-mm-dd';status(s.getRange('K6:K105'),['未开始','待复核','通过','未通过']);
s=sheet(w2,'03-规则版本','规则与版本记录','规则变更后必须进行影响分析和回归测试。',['规则编号','项目','规则说明','阈值','生效日','版本','修改原因','修改人','复核人','回归结果','状态'],Array.from({length:80},(_,i)=>[`RULE-${String(i+1).padStart(3,'0')}`,'','','',null,'','','','','','草稿']),{A:14,B:14,C:40,D:16,E:14,F:10,G:32,H:14,I:14,J:16,K:12},'RuleVersions');s.getRange('B6:K85').format.fill=yellow;s.getRange('E6:E85').format.numberFormat='yyyy-mm-dd';s.getRange('K6:K85').dataValidation={rule:{type:'list',values:['草稿','待审批','生效','停用']}};
s=sheet(w2,'04-运行日志','自动化运行日志','每次运行保留输入、规则、结果、异常和复核。',['运行编号','项目','期间','输入版本','规则版本','开始时间','结束时间','输入行数','通过行数','异常行数','是否完整','日志路径','执行人','复核人'],Array.from({length:100},(_,i)=>[`RUN-${String(i+1).padStart(4,'0')}`,'','','','','','','','','','待判断','','','']),{A:15,B:14,C:12,D:20,E:14,F:18,G:18,H:12,I:12,J:12,K:13,L:34,M:14,N:14},'RunLog');s.getRange('B6:N105').format.fill=yellow;s.getRange('K6:K105').dataValidation={rule:{type:'list',values:['是','否','待判断']}};
s=sheet(w2,'05-Issue与关闭','自动化Issue与关闭','Resolved不等于Closed，必须验证修复和影响范围。',['Issue号','项目','发现日','问题','影响范围','临时措施','Owner','截止日','状态','根因','修复版本','回归证据','复核人','关闭日'],Array.from({length:80},(_,i)=>[`ISS-${String(i+1).padStart(3,'0')}`,'',null,'','','','',null,'Open','','','','',null]),{A:14,B:14,C:14,D:34,E:28,F:34,G:14,H:14,I:14,J:34,K:14,L:34,M:14,N:14},'Issues');s.getRange('B6:N85').format.fill=yellow;s.getRange('C6:C85').format.numberFormat='yyyy-mm-dd';s.getRange('H6:H85').format.numberFormat='yyyy-mm-dd';s.getRange('N6:N85').format.numberFormat='yyyy-mm-dd';s.getRange('I6:I85').dataValidation={rule:{type:'list',values:['Open','In Progress','Resolved','Closed','Accepted Risk']}};
await exportBook(w2,'财务自动化UAT与控制工具.xlsx','uat',['00-UAT看板','01-项目清单','02-UAT测试','03-规则版本','04-运行日志','05-Issue与关闭']);

// Security workbook
const w3=Workbook.create();s=w3.worksheets.add('00-安全总览');title(s,'财务AI与自动化安全清单','先判断数据等级、授权范围和处理环境，再决定是否使用AI、Python、RPA或云服务。',7);s.getRange('A5:D5').values=[['原则','要求','责任人','证据']];head(s,'A5:D5');s.getRange('A6:D12').values=[['最小化','只取必要字段','数据Owner','字段清单'],['脱敏','名称、账号和身份信息掩码','执行人','脱敏样例'],['本地化','敏感数据优先本地处理','IT/财务','环境批准'],['权限化','开发、运行、复核、批准分离','主管','权限矩阵'],['可追溯','输入、规则、输出和日志完整','Owner','运行包'],['可回退','工具失败可手工完成','流程Owner','Fallback测试'],['禁止凭证','密码、U盾、私钥不进入AI','所有人员','培训记录']];body(s,'A6:D12');widths(s,{A:18,B:46,C:18,D:36});
s=sheet(w3,'01-数据分级','财务数据分级','L5高敏感凭证禁止交给AI或普通自动化。',['数据类型','等级','示例','是否允许AI','脱敏要求','权限要求','人工复核'],d.security,{A:18,B:10,C:34,D:20,E:34,F:32,G:30},'DataClass');
let secRows=[['SEC-001','网银密码','L5','否','禁止存储或传递','仅授权人员','无','禁止',''],['SEC-002','U盾凭据','L5','否','禁止','职责分离','无','禁止',''],['SEC-003','税务登录凭证','L5','否','禁止','税务责任人','无','禁止',''],['SEC-004','工资明细','L4','严格限制','掩码姓名和账号','HR/薪酬','逐项','本地处理',''],['SEC-005','未公开报表','L3','经批准','删除主体标识','财务管理层','关键数字','限制上传',''],['SEC-006','客户交易明细','L3','经批准','客户匿名化','业务Owner','抽样','最小字段',''],['SEC-007','公开政策','L1','是','无','一般','核实日期','允许','']];while(secRows.length<60)secRows.push([`SEC-${String(secRows.length+1).padStart(3,'0')}`,'','','','','','','','']);
s=sheet(w3,'02-安全检查清单','AI与自动化安全检查','每个新项目上线前完成。',['编号','数据或事项','等级','AI使用','脱敏','权限','复核','处理结论','证据'],secRows,{A:13,B:28,C:10,D:16,E:32,F:28,G:22,H:18,I:34},'SecurityChecklist');s.getRange('B6:I65').format.fill=yellow;
s=sheet(w3,'03-权限矩阵','自动化权限矩阵','准备、复核和批准应分离。',['动作','执行工具/人员','可否自动','复核人','批准人','日志','停止条件'],[['读取已批准导出文件','脚本/查询','可以','制表人','流程Owner','需要','字段或期间不符'],['生成匹配建议','规则工具','可以','业务财务','流程Owner','需要','低置信度'],['生成凭证草稿','ERP接口','条件允许','总账','财务主管','需要','重大或异常分录'],['正式过账','授权财务','不默认自动','复核人','财务主管','需要','任何异常'],['准备付款建议','规则工具','可以','AP/资金','授权审批人','需要','账户变化或大额'],['批准或执行付款','授权人员','否','独立复核','授权审批人','需要','权限不完整'],['准备申报数据','规则工具','可以','税务会计','税务负责人','需要','账票税差异'],['提交税务申报','税务责任人','否','复核人','授权责任人','需要','未完成复核']],{A:28,B:22,C:14,D:18,E:18,F:12,G:34},'PermissionMatrix');
s=sheet(w3,'04-供应商与云服务','外部工具评估','使用ChatGPT、Codex、云OCR、RPA或API前完成。',['工具/供应商','使用目的','数据等级','存储位置','是否用于训练','保留期限','访问控制','合同条款','批准人','结论'],Array.from({length:30},()=>['','','','','','','','','','待评估']),{A:22,B:32,C:12,D:24,E:16,F:14,G:24,H:34,I:14,J:14},'VendorReview');s.getRange('A6:J35').format.fill=yellow;s.getRange('J6:J35').dataValidation={rule:{type:'list',values:['待评估','允许','限制使用','禁止']}};
await exportBook(w3,'财务AI与自动化安全清单.xlsx','security',['00-安全总览','01-数据分级','02-安全检查清单','03-权限矩阵','04-供应商与云服务']);

// Five project exercise workbooks
function addProjectReadme(w,titleText,scope){let s=w.worksheets.add('00-说明');title(s,titleText,'先理解字段和规则，再运行工具。自动输出必须人工复核。',5);s.getRange('A5:B5').values=[['项目','说明']];head(s,'A5:B5');s.getRange('A6:B12').values=[['业务目标',scope],['使用顺序','输入→规则→结果→UAT'],['黄色单元格','可以修改的输入或人工结论'],['自动化边界','只生成建议或异常清单'],['最终责任','财务复核，授权人员批准'],['失败回退','恢复原始数据并按手工流程完成'],['版本','2026-09-11']];body(s,'A6:B12');widths(s,{A:22,B:72});return s}
async function exerciseBank(){const w=Workbook.create();addProjectReadme(w,'银行自动对账练习','银行流水与ERP银行明细匹配并输出未匹配项。');let x=sheet(w,'01-银行流水','银行流水','正数为收款，负数为付款。',['银行ID','日期','借方','贷方','摘要','对方户名','净额'],d.samples.bank.bank.map((r,i)=>[...r,`=D${i+6}-C${i+6}`]),{A:12,B:14,C:14,D:14,E:34,F:22,G:14},'BankData');x.getRange('B6:B12').format.numberFormat='yyyy-mm-dd';x.getRange('A6:F12').format.fill=yellow;x=sheet(w,'02-ERP明细','ERP银行明细','amount正数为收款，负数为付款。',['ERP ID','日期','金额','摘要','对方户名'],d.samples.bank.erp,{A:12,B:14,C:14,D:34,E:22},'ERPBank');x.getRange('B6:B9').format.numberFormat='yyyy-mm-dd';x.getRange('A6:E9').format.fill=yellow;x=sheet(w,'03-预期结果','预期匹配结果','用于验证Power Query或Python输出。',['银行ID','ERP ID','匹配类型','置信度','原因'],d.samples.bank.expected,{A:16,B:14,C:18,D:12,E:46},'BankExpected');x.getRange('D6:D11').format.numberFormat='0%';x=sheet(w,'04-UAT','银行对账UAT','修改输入后记录实际结果。',['案例','场景','预期','实际','结果','复核人'],[['B-U01','唯一金额日期一致','精确匹配','','待复核',''],['B-U02','跨日1天','跨日候选','','待复核',''],['B-U03','手续费','银行单边','','待复核',''],['B-U04','两笔对一笔','组合候选','','待复核',''],['B-U05','重复金额','不得任意配对','','待复核','']],{A:12,B:28,C:24,D:34,E:12,F:14},'BankUAT');x.getRange('D6:F10').format.fill=yellow;status(x.getRange('E6:E10'),['待复核','通过','未通过']);await exportBook(w,path.join('财务自动化实战项目包','01-银行自动对账','银行自动对账练习.xlsx'),'ex_bank',['00-说明','01-银行流水','02-ERP明细','03-预期结果','04-UAT'])}
async function exerciseAccrual(){const w=Workbook.create();addProjectReadme(w,'暂估自动匹配练习','匹配暂估、采购订单、入库与到票，并识别差异和长期未冲。');let x=sheet(w,'01-暂估','暂估明细','不含税金额。',['暂估ID','期间','供应商','PO','入库单','物料','数量','单价','金额','状态'],d.samples.accrual.accrual,{A:12,B:12,C:14,D:13,E:13,F:12,G:10,H:12,I:14,J:11},'AccrualTable');x.getRange('A6:J9').format.fill=yellow;x=sheet(w,'02-发票','发票明细','发票到达不等于可以自动冲暂估。',['发票ID','日期','供应商','PO','物料','数量','单价','金额','税额'],d.samples.accrual.invoice,{A:12,B:14,C:14,D:13,E:12,F:10,G:12,H:14,I:12},'InvoiceTable');x.getRange('A6:I8').format.fill=yellow;x=sheet(w,'03-预期结果','预期匹配结果','供应商不一致和差异项目必须人工处理。',['暂估ID','发票ID','结果','金额差异','行动'],d.samples.accrual.expected,{A:14,B:14,C:18,D:14,E:58},'AccrualExpected');x.getRange('D6:D9').format.numberFormat='#,##0.00';await exportBook(w,path.join('财务自动化实战项目包','02-暂估自动匹配','暂估自动匹配练习.xlsx'),'ex_accrual',['00-说明','01-暂估','02-发票','03-预期结果'])}
async function exerciseAging(){const w=Workbook.create();addProjectReadme(w,'长期挂账扫描练习','按账龄、余额方向和责任部门输出清理优先级。');let x=sheet(w,'01-往来明细','往来明细','余额方向异常只能提示，不能机械重分类。',['项目ID','科目','单位','业务日期','借方余额','贷方余额','责任部门'],d.samples.aging.balances,{A:13,B:18,C:14,D:14,E:14,F:14,G:16},'BalanceTable');x.getRange('D6:D11').format.numberFormat='yyyy-mm-dd';x.getRange('A6:G11').format.fill=yellow;x=sheet(w,'02-预期结果','预期异常结果','高优先级需明确Owner、原因和关闭证据。',['项目ID','账龄段','优先级','行动'],d.samples.aging.expected,{A:14,B:18,C:12,D:70},'AgingExpected');x.getRange('C6:C11').conditionalFormats.add('containsText',{text:'高',format:{fill:red,font:{bold:true,color:'#C00000'}}});await exportBook(w,path.join('财务自动化实战项目包','03-长期挂账扫描','长期挂账扫描练习.xlsx'),'ex_aging',['00-说明','01-往来明细','02-预期结果'])}
async function exerciseTB(){const w=Workbook.create();addProjectReadme(w,'全科目异常检查练习','导入TB并按规则输出异常，人工判断是否调账、调表或无需处理。');let x=sheet(w,'01-TB','试算平衡表','direction表示余额方向。',['科目编码','科目名称','方向','余额','辅助维度'],d.samples.tb.tb,{A:16,B:28,C:10,D:16,E:18},'TBTable');x.getRange('A6:E12').format.fill=yellow;x=sheet(w,'02-规则库','异常规则库','规则必须有编号、阈值、处理动作和版本。',['规则ID','科目前缀','条件','阈值','规则名称','建议动作'],d.samples.tb.rules,{A:12,B:14,C:12,D:12,E:28,F:62},'RuleTable');x.getRange('A6:F10').format.fill=yellow;x=sheet(w,'03-预期结果','预期异常结果','应收贷方先查实质，不能自动转合同负债。',['科目编码','规则ID','优先级','行动'],d.samples.tb.expected,{A:16,B:12,C:12,D:70},'TBExpected');await exportBook(w,path.join('财务自动化实战项目包','04-全科目异常检查','全科目异常检查练习.xlsx'),'ex_tb',['00-说明','01-TB','02-规则库','03-预期结果'])}
async function exerciseFS(){const w=Workbook.create();addProjectReadme(w,'财务报表自动勾稽练习','检查四张报表、权益滚动、TB映射和期初期末衔接。');let x=sheet(w,'01-报表数据','报表数据','故意设置部分差异，练习定位。',['报表','项目','金额'],d.samples.fs.data,{A:20,B:34,C:18},'FSData');x.getRange('A6:C16').format.fill=yellow;x=sheet(w,'02-预期结果','预期校验结果','差异为0才表示该项公式勾稽通过。',['检查ID','检查名称','差异','状态','公式逻辑'],d.samples.fs.expected,{A:12,B:28,C:16,D:14,E:48},'FSExpected');x.getRange('C6:C9').format.numberFormat='#,##0.00';x.getRange('D6:D9').conditionalFormats.add('containsText',{text:'未通过',format:{fill:red,font:{bold:true,color:'#C00000'}}});await exportBook(w,path.join('财务自动化实战项目包','05-财务报表自动勾稽','财务报表自动勾稽练习.xlsx'),'ex_fs',['00-说明','01-报表数据','02-预期结果'])}
await exerciseBank();await exerciseAccrual();await exerciseAging();await exerciseTB();await exerciseFS();
console.log(JSON.stringify({centralWorkbooks:3,exerciseWorkbooks:5}));

